//
// Generated file, do not edit! Created by opp_msgc 4.2 from messages/RangPkt.msg.
//

#ifndef _RANGPKT_M_H_
#define _RANGPKT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "ApplPkt_m.h"
#include "Coord.h"
// }}



/**
 * Class generated from <tt>messages/RangPkt.msg</tt> by opp_msgc.
 * <pre>
 * packet RangPkt extends ApplPkt {
 *     int RangingMethodId;
 *     Coord coordenadas;
 * }
 * </pre>
 */
class RangPkt : public ::ApplPkt
{
  protected:
    int RangingMethodId_var;
    Coord coordenadas_var;

  private:
    void copy(const RangPkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RangPkt&);

  public:
    RangPkt(const char *name=NULL, int kind=0);
    RangPkt(const RangPkt& other);
    virtual ~RangPkt();
    RangPkt& operator=(const RangPkt& other);
    virtual RangPkt *dup() const {return new RangPkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getRangingMethodId() const;
    virtual void setRangingMethodId(int RangingMethodId);
    virtual Coord& getCoordenadas();
    virtual const Coord& getCoordenadas() const {return const_cast<RangPkt*>(this)->getCoordenadas();}
    virtual void setCoordenadas(const Coord& coordenadas);
};

inline void doPacking(cCommBuffer *b, RangPkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RangPkt& obj) {obj.parsimUnpack(b);}


#endif // _RANGPKT_M_H_
