MiXiM: BaseMacLayer Class Reference
BaseMacLayer Class Reference
[macLayer - MAC layer modules, baseModules - base module classes of MiXiM]
A very simple MAC module template which provides de- and encapsulation of messages using the standard addresses. It also provides basic handling of lower layer messages.
#include <BaseMacLayer.h>
Inherits BaseLayer.
Inherited by BMacLayer, csma, CSMAMacLayer, LMacLayer, Mac80211, and UWBIRMac.
Public Types
enum BaseMacMessageKinds { LAST_BASE_MAC_MESSAGE_KIND = 23000 }
Message kinds used by this layer.
enum BaseMacControlKinds { TX_OVER = 23500, PACKET_DROPPED, LAST_BASE_MAC_CONTROL_KIND }
Control message kinds used by this layer.
Public Member Functions
BaseMacLayer (unsigned stacksize)
virtual void initialize (int)
Initialization of the module and some variables.
const LAddress::L2Type & getMACAddress () const
Returns the MAC address of this MAC module.
Protected Member Functions
virtual void registerInterface ()
Registers this bridge's NIC with INET's InterfaceTable.
virtual void handleUpperMsg (cMessage *msg)
Handle messages comming from the network layer.
virtual void handleLowerMsg (cMessage *msg)
virtual void handleSelfMsg (cMessage *)
Handle self messages such as timer...
virtual void handleLowerControl (cMessage *msg)
Handle control messages from lower layer.
virtual void handleUpperControl (cMessage *)
Handle control messages from upper layer.
virtual cPacket * decapsMsg (MacPkt *)
decapsulate the network message from the MacPkt
virtual MacPkt * encapsMsg (cPacket *)
Encapsulate the NetwPkt into an MacPkt.
virtual Signal * createSignal (simtime_t_cref start, simtime_t_cref length, double power, double bitrate)
Creates a simple Signal defined over time with the passed parameters.
Mapping * createConstantMapping (simtime_t_cref start, simtime_t_cref end, Argument::mapped_type_cref value)
Creates a simple Mapping with a constant curve progression at the passed value.
Mapping * createRectangleMapping (simtime_t_cref start, simtime_t_cref end, Argument::mapped_type_cref value)
Creates a simple Mapping with a constant curve progression at the passed value and discontinuities at the boundaries.
ConstMapping * createSingleFrequencyMapping (simtime_t_cref start, simtime_t_cref end, Argument::mapped_type_cref centerFreq, Argument::mapped_type_cref bandWith, Argument::mapped_type_cref value)
Creates a Mapping defined over time and frequency with constant power in a certain frequency band.
BaseConnectionManager * getConnectionManager () const
Returns a pointer to this MACs NICs ConnectionManager module.
virtual const LAddress::L2Type & getUpperDestinationFromControlInfo (const cObject *const pCtrlInfo) const
Extracts the MAC address from the "control info" structure (object).
virtual cObject * setUpControlInfo (cMessage *const pMsg, const LAddress::L2Type &pSrcAddr)
Attaches a "control info" (MacToNetw) structure (object) to the message pMsg.
virtual cObject * setDownControlInfo (cMessage *const pMsg, Signal *const pSignal)
Attaches a "control info" (MacToPhy) structure (object) to the message pMsg.
const cModule * getNic () const
Pointer to nic Module.
cModule * getNic ()
Protected Attributes
MacToPhyInterface * phy
Handler to the physical layer.
int headerLength
Pointer to the arp module.
LAddress::L2Type myMacAddr
MAC address.
bool coreDebug
debug this core module?
int phyHeaderLength
The length of the phy header (in bits).
Private Member Functions
BaseMacLayer (const BaseMacLayer &)
Copy constructor is not allowed.
BaseMacLayer & operator= (const BaseMacLayer &)
Assignment operator is not allowed.
Detailed Description
A very simple MAC module template which provides de- and encapsulation of messages using the standard addresses. It also provides basic handling of lower layer messages.
Author:
Daniel Willkomm, Karl Wessel
Definition at line 45 of file BaseMacLayer.h.
Member Enumeration Documentation
enum BaseMacLayer::BaseMacControlKinds
Control message kinds used by this layer.
Enumerator:
TX_OVER
Indicates the end of a transmission
PACKET_DROPPED
Tells the netw layer that a packet to be sent has been dropped.
LAST_BASE_MAC_CONTROL_KIND
Stores the id on which classes extending BaseMac should continue their own control kinds.
Definition at line 55 of file BaseMacLayer.h.
{
        TX_OVER = 23500,
        PACKET_DROPPED,
        LAST_BASE_MAC_CONTROL_KIND,
    };
enum BaseMacLayer::BaseMacMessageKinds
Message kinds used by this layer.
Enumerator:
LAST_BASE_MAC_MESSAGE_KIND
Stores the id on which classes extending BaseMac should continue their own message kinds.
Definition at line 49 of file BaseMacLayer.h.
{
        LAST_BASE_MAC_MESSAGE_KIND = 23000,
    };
Member Function Documentation
Mapping * BaseMacLayer::createConstantMapping (simtime_t_cref start, simtime_t_cref end, Argument::mapped_type_cref value) [protected]
Creates a simple Mapping with a constant curve progression at the passed value.
Used by "createSignal" to create the bitrate mapping.
Definition at line 242 of file BaseMacLayer.cc.
References MappingUtils::createMapping(), Mapping::LINEAR, Argument::MappedZero, Mapping::setValue(), and DimensionSet::timeDomain.
Referenced by createSignal().
{
  //create mapping over time
  Mapping* m = MappingUtils::createMapping(Argument::MappedZero, DimensionSet::timeDomain, Mapping::LINEAR);
  //set position Argument
  Argument startPos(start);
  //set mapping at position
  m->setValue(startPos, value);
  //set position Argument
  Argument endPos(end);
  //set mapping at position
  m->setValue(endPos, value);
  return m;
}
Mapping * BaseMacLayer::createRectangleMapping (simtime_t_cref start, simtime_t_cref end, Argument::mapped_type_cref value) [protected]
Creates a simple Mapping with a constant curve progression at the passed value and discontinuities at the boundaries.
Used by "createSignal" to create the power mapping.
Definition at line 262 of file BaseMacLayer.cc.
References MappingUtils::addDiscontinuity(), MappingUtils::createMapping(), Mapping::LINEAR, Argument::MappedZero, MappingUtils::post(), MappingUtils::pre(), and DimensionSet::timeDomain.
Referenced by createSignal().
{
  //create mapping over time
  Mapping* m = MappingUtils::createMapping(DimensionSet::timeDomain, Mapping::LINEAR);
  //set position Argument
  Argument startPos(start);
  //set discontinuity at position
  MappingUtils::addDiscontinuity(m, startPos, Argument::MappedZero, MappingUtils::post(start), value);
  //set position Argument
  Argument endPos(end);
  //set discontinuity at position
  MappingUtils::addDiscontinuity(m, endPos, Argument::MappedZero, MappingUtils::pre(end), value);
  return m;
}
Signal * BaseMacLayer::createSignal (simtime_t_cref start, simtime_t_cref length, double power, double bitrate) [protected, virtual]
Creates a simple Signal defined over time with the passed parameters.
Convenience method to be able to create the appropriate Signal for the MacToPhyControlInfo without needing to care about creating Mappings.
NOTE: The created signal's transmission-power is a rectangular function. This method uses MappingUtils::addDiscontinuity to represent the discontinuities at the beginning and end of this rectangular function. Because of this the created mapping which represents the signal's transmission-power is still zero at the exact start and end. Please see the method MappingUtils::addDiscontinuity for the reason.
Reimplemented in Mac80211.
Definition at line 225 of file BaseMacLayer.cc.
References createConstantMapping(), createRectangleMapping(), Signal::setBitrate(), and Signal::setTransmissionPower().
Referenced by LMacLayer::attachSignal(), BMacLayer::attachSignal(), and CSMAMacLayer::encapsMsg().
{
  simtime_t end = start + length;
  //create signal with start at current simtime and passed length
  Signal* s = new Signal(start, length);
  //create and set tx power mapping
  Mapping* txPowerMapping = createRectangleMapping(start, end, power);
  s->setTransmissionPower(txPowerMapping);
  //create and set bitrate mapping
  Mapping* bitrateMapping = createConstantMapping(start, end, bitrate);
  s->setBitrate(bitrateMapping);
  return s;
}
cPacket * BaseMacLayer::decapsMsg (MacPkt * msg) [protected, virtual]
decapsulate the network message from the MacPkt
Decapsulates the network packet from the received MacPkt
Reimplemented in csma, CSMA802154, and Mac80211.
Definition at line 129 of file BaseMacLayer.cc.
References setUpControlInfo().
Referenced by CSMAMacLayer::handleLowerMsg(), AlohaMacLayer::handleLowerMsg(), handleLowerMsg(), LMacLayer::handleSelfMsg(), and BMacLayer::handleSelfMsg().
{
    cPacket *m = msg->decapsulate();
    setUpControlInfo(m, msg->getSrcAddr());
    // delete the macPkt
    delete msg;
    coreEV << " message decapsulated " << endl;
    return m;
}
MacPkt * BaseMacLayer::encapsMsg (cPacket * netwPkt) [protected, virtual]
Encapsulate the NetwPkt into an MacPkt.
Encapsulates the received NetwPkt into a MacPkt and set all needed header fields.
Reimplemented in AlohaMacLayer, CSMAMacLayer, LMacLayer, and Mac80211.
Definition at line 143 of file BaseMacLayer.cc.
References getUpperDestinationFromControlInfo(), headerLength, and myMacAddr.
Referenced by handleUpperMsg().
{
    MacPkt *pkt = new MacPkt(netwPkt->getName(), netwPkt->getKind());
    pkt->setBitLength(headerLength);
    // copy dest address from the Control Info attached to the network
    // message by the network layer
    cObject* cInfo = netwPkt->removeControlInfo();
    coreEV <<"CInfo removed, mac addr="<< getUpperDestinationFromControlInfo(cInfo) << endl;
    pkt->setDestAddr(getUpperDestinationFromControlInfo(cInfo));
    //delete the control info
    delete cInfo;
    //set the src address to own mac address (nic module getId())
    pkt->setSrcAddr(myMacAddr);
    //encapsulate the network packet
    pkt->encapsulate(netwPkt);
    coreEV <<"pkt encapsulated\n";
    return pkt;
}
BaseConnectionManager * BaseMacLayer::getConnectionManager () const [protected]
Returns a pointer to this MACs NICs ConnectionManager module.
Returns:
pointer to the connection manager module
Definition at line 306 of file BaseMacLayer.cc.
References getNic().
Referenced by Mac80211::initialize(), and csma::initialize().
{
  return ChannelAccess::getConnectionManager(getNic());
}
const LAddress::L2Type & BaseMacLayer::getUpperDestinationFromControlInfo (const cObject *const pCtrlInfo) const [protected, virtual]
Extracts the MAC address from the "control info" structure (object).
Extract the destination MAC address from the "control info" which was prev. set by NetwToMacControlInfo::setControlInfo().
Parameters:
pCtrlInfo The "control info" structure (object) prev. set by NetwToMacControlInfo::setControlInfo().
Returns:
The MAC address of message receiver.
Definition at line 310 of file BaseMacLayer.cc.
References NetwToMacControlInfo::getDestFromControlInfo().
Referenced by BMacLayer::addToQueue(), Mac80211::encapsMsg(), LMacLayer::encapsMsg(), AlohaMacLayer::encapsMsg(), encapsMsg(), and csma::handleUpperMsg().
{
  return NetwToMacControlInfo::getDestFromControlInfo(pCtrlInfo);
}
void BaseMacLayer::handleLowerMsg (cMessage * msg) [protected, virtual]
If message arrives from lower layer, check whether it is for us. Send it up if yes.
This basic implementation just forwards all message that are broadcast (destAddr = L2BROADCAST) or destined for this node (destAddr = nic module getId()) to the network layer
See also:
sendUp
Implements BaseLayer.
Reimplemented in AlohaMacLayer, BMacLayer, csma, CSMAMacLayer, LMacLayer, and Mac80211.
Definition at line 189 of file BaseMacLayer.cc.
References decapsMsg(), LAddress::isL2Broadcast(), myMacAddr, and BaseLayer::sendUp().
{
    MacPkt*          mac  = static_cast<MacPkt *>(msg);
    LAddress::L2Type dest = mac->getDestAddr();
    LAddress::L2Type src  = mac->getSrcAddr();
    //only foward to upper layer if message is for me or broadcast
    if((dest == myMacAddr) || LAddress::isL2Broadcast(dest)) {
    coreEV << "message with mac addr " << src
         << " for me (dest=" << dest
         << ") -> forward packet to upper layer\n";
    sendUp(decapsMsg(mac));
    }
    else{
    coreEV << "message with mac addr " << src
         << " not for me (dest=" << dest
         << ") -> delete (my MAC="<<myMacAddr<<")\n";
    delete mac;
    }
}
void BaseMacLayer::handleUpperMsg (cMessage * mac) [protected, virtual]
Handle messages comming from the network layer.
Here is the place to implement a real medium access functionality.
If message arrives from upper layer, make a MAC packet from it (encapsMsg) and send it down (sendDown).
See also:
encapsMsg, sendDown
Redefine this function if you want to process messages from upper layers before they are send to lower layers.
To forward the message to lower layers after processing it please use sendDown. It will take care of anything needed
Implements BaseLayer.
Reimplemented in BMacLayer, csma, CSMAMacLayer, LMacLayer, and Mac80211.
Definition at line 175 of file BaseMacLayer.cc.
References encapsMsg(), and BaseLayer::sendDown().
{
  assert(dynamic_cast<cPacket*>(mac));
    sendDown(encapsMsg(static_cast<cPacket*>(mac)));
}
void BaseMacLayer::initialize (int stage) [virtual]
Initialization of the module and some variables.
First we have to initialize the module from which we derived ours, in this case BaseLayer.
Reimplemented from BaseLayer.
Reimplemented in AlohaMacLayer, BMacLayer, csma, CSMA802154, CSMAMacLayer, LMacLayer, Mac80211, Mac80211MultiChannel, and UWBIRMac.
Definition at line 50 of file BaseMacLayer.cc.
References coreDebug, BaseModule::findHost(), getNic(), MacToPhyInterface::getPhyHeaderLength(), headerLength, LAddress::L2NULL, AddressingInterface::myMacAddr(), myMacAddr, phy, phyHeaderLength, and registerInterface().
{
    BaseLayer::initialize(stage);
    if(stage==0)
    {
      // get handle to phy layer
        if ((phy = FindModule<MacToPhyInterface*>::findSubModule(getNic())) == NULL) {
          error("Could not find a PHY module.");
        }
        headerLength    = par("headerLength");
        phyHeaderLength = phy->getPhyHeaderLength();
        hasPar("coreDebug") ? coreDebug = par("coreDebug").boolValue() : coreDebug = false;
    }
    if (myMacAddr == LAddress::L2NULL) {
      // see if there is an addressing module available
        // otherwise use NIC modules id as MAC address
        AddressingInterface* addrScheme = FindModule<AddressingInterface*>::findSubModule(findHost());
        if(addrScheme) {
            myMacAddr = addrScheme->myMacAddr(this);
        } else {
            const std::string addressString = par("address").stringValue();
            if (addressString.empty() || addressString == "auto")
                myMacAddr = LAddress::L2Type(getNic()->getId());
            else
                myMacAddr = LAddress::L2Type(addressString.c_str());
            // use streaming operator for string conversion, this makes it more
            // independent from the myMacAddr type
            std::ostringstream oSS; oSS << myMacAddr;
            par("address").setStringValue(oSS.str());
        }
        registerInterface();
    }
}
cObject * BaseMacLayer::setDownControlInfo (cMessage *const pMsg, Signal *const pSignal) [protected, virtual]
Attaches a "control info" (MacToPhy) structure (object) to the message pMsg.
This is most useful when passing packets between protocol layers of a protocol stack, the control info will contain the signal.
The "control info" object will be deleted when the message is deleted. Only one "control info" structure can be attached (the second setL3ToL2ControlInfo() call throws an error).
Parameters:
pMsg The message where the "control info" shall be attached.
pSignal The signal which should be send.
Definition at line 325 of file BaseMacLayer.cc.
References MacToPhyControlInfo::setControlInfo().
Referenced by LMacLayer::attachSignal(), BMacLayer::attachSignal(), CSMAMacLayer::encapsMsg(), Mac80211::sendACKframe(), Mac80211::sendBROADCASTframe(), Mac80211::sendCTSframe(), Mac80211::sendDATAframe(), and Mac80211::sendRTSframe().
{
  return MacToPhyControlInfo::setControlInfo(pMsg, pSignal);
}
cObject * BaseMacLayer::setUpControlInfo (cMessage *const pMsg, const LAddress::L2Type & pSrcAddr) [protected, virtual]
Attaches a "control info" (MacToNetw) structure (object) to the message pMsg.
This is most useful when passing packets between protocol layers of a protocol stack, the control info will contain the destination MAC address.
The "control info" object will be deleted when the message is deleted. Only one "control info" structure can be attached (the second setL3ToL2ControlInfo() call throws an error).
Parameters:
pMsg The message where the "control info" shall be attached.
pSrcAddr The MAC address of the message receiver.
Definition at line 317 of file BaseMacLayer.cc.
References MacToNetwControlInfo::setControlInfo().
Referenced by Mac80211::decapsMsg(), csma::decapsMsg(), and decapsMsg().
{
  return MacToNetwControlInfo::setControlInfo(pMsg, pSrcAddr);
}
Member Data Documentation
int BaseMacLayer::headerLength [protected]
Pointer to the arp module.
Length of the MacPkt header
Reimplemented in BMacLayer.
Definition at line 76 of file BaseMacLayer.h.
Referenced by LMacLayer::encapsMsg(), AlohaMacLayer::encapsMsg(), encapsMsg(), LMacLayer::handleSelfMsg(), csma::handleUpperMsg(), LMacLayer::initialize(), and initialize().
int BaseMacLayer::phyHeaderLength [protected]
The length of the phy header (in bits).
Since the MAC layer has to create the signal for a transmission it has to know the total length of the packet and therefore needs the length of the phy header.
Definition at line 93 of file BaseMacLayer.h.
Referenced by initialize(), and Mac80211::packetDuration().
The documentation for this class was generated from the following files:
src/base/modules/BaseMacLayer.h
src/base/modules/BaseMacLayer.cc