MiXiM: Dimension Class Reference
Dimension Class Reference
[mapping - classes representing mathematical mappings]
Specifies a dimension for mappings (like time, frequency, etc.).
#include <MappingBase.h>
Public Types
typedef std::map< std::string,
int > DimensionIDMap
Type for map from dimension name to ID.
typedef DimensionIDMap::key_type DimensionNameType
typedef DimensionIDMap::mapped_type DimensionIdType
Public Member Functions
Dimension (const DimensionNameType &name)
Creates a new dimension instance representing the dimension with the passed name.
bool operator== (const Dimension &other) const
Returns true if the ids of the two dimensions are equal.
bool operator< (const Dimension &other) const
Returns true if the id of the other dimension is greater then the id of this dimension.
bool operator<= (const Dimension &other) const
Sorting operator by dimension ID.
bool operator> (const Dimension &other) const
Sorting operator by dimension ID.
bool operator>= (const Dimension &other) const
Sorting operator by dimension ID.
bool operator!= (const Dimension &other) const
Sorting operator by dimension ID.
DimensionNameType getName () const
Returns the name of this dimension.
DimensionIdType getID () const
Returns the unique id of the dimension this instance represents.
Static Public Member Functions
static Dimension & time_static ()
Shortcut to the time Dimension, same as 'Dimension("time")', but spares the parsing of a string.
static Dimension & frequency_static ()
Shortcut to the frequency Dimension, same as 'Dimension("frequency")', but spares the parsing of a string.
Static Public Attributes
static const Dimension time = Dimension::time_static()
Shortcut to the time Dimension, same as 'Dimension("time")', but spares the parsing of a string.
static const Dimension frequency = Dimension::frequency_static()
Shortcut to the frequency Dimension, same as 'Dimension("frequency")', but spares the parsing of a string.
Protected Types
typedef std::map
< DimensionIdType,
DimensionNameType > DimensionNameMap
Type for map from ID to dimension name.
Static Protected Member Functions
static DimensionIDMap & dimensionIDs ()
stores the registered dimensions ids.
static DimensionNameMap & dimensionNames ()
Mapping from id to name of registered dimensions.
static DimensionIdType & nextFreeID ()
Stores the next free ID for a new dimension.
static int getDimensionID (const DimensionNameType &name)
Returns an instance of dimension which represents the dimension with the passed name.
Protected Attributes
DimensionIdType id
The unique id of the dimension this instance represents.
Friends
std::ostream & operator<< (std::ostream &out, const Dimension &d)
Output operator for a dimension.
Detailed Description
Specifies a dimension for mappings (like time, frequency, etc.).
The dimension is represented external by a string (like "time") and internally by an unique ID.
Note: Since the ID for a Dimensions is set the first time an instance of this dimensions is created and the id is used to provide a defined ordering of the Dimensions it DOES matter which dimensions are instantiated the first time. Only the time dimension will always have zero as unique id.
Author:
Karl Wessel
Definition at line 31 of file MappingBase.h.
Member Function Documentation
Dimension::DimensionIDMap & Dimension::dimensionIDs () [static, protected]
stores the registered dimensions ids.
Uses "construct-on-first-use" idiom to ensure correct initialization of static members.
Definition at line 15 of file MappingBase.cc.
Referenced by getDimensionID().
{
  //use "construct-on-first-use" idiom to ensure correct order of
  //static initialization
  static DimensionIDMap* dimIDs = new DimensionIDMap();
  return *dimIDs;
}
Dimension::DimensionNameMap & Dimension::dimensionNames () [static, protected]
Mapping from id to name of registered dimensions.
Uses "construct-on-first-use" idiom to ensure correct initialization of static members.
Definition at line 22 of file MappingBase.cc.
Referenced by getDimensionID(), and getName().
{
  //use "construct-on-first-use" idiom to ensure correct order of
  //static initialization
  static DimensionNameMap* names = new DimensionNameMap();
  return *names;
}
Dimension & Dimension::frequency_static () [static]
Shortcut to the frequency Dimension, same as 'Dimension("frequency")', but spares the parsing of a string.
This method should be used instead of the static "frequency" member when used during initialization of static variables since it assures the correct order of initialization.
Definition at line 36 of file MappingBase.cc.
{
  static Dimension* freq = new Dimension("frequency");
  return *freq;
}
DimensionIdType Dimension::getID () const [inline]
Returns the unique id of the dimension this instance represents.
The id is used to uniquely identify dimensions as well as to provide a sorting of dimensions. Note: The "time"-dimension will always have the ID zero.
Definition at line 155 of file MappingBase.h.
{ return id; }
Dimension::DimensionIdType & Dimension::nextFreeID () [static, protected]
Stores the next free ID for a new dimension.
Uses "construct-on-first-use" idiom to ensure correct initialization of static members.
Definition at line 10 of file MappingBase.cc.
Referenced by getDimensionID().
{
  static Dimension::DimensionIdType* nextID = new Dimension::DimensionIdType(1);
  return *nextID;
}
bool Dimension::operator< (const Dimension & other) const [inline]
Returns true if the id of the other dimension is greater then the id of this dimension.
This is needed to be able to use Dimension as a key in std::map.
Definition at line 128 of file MappingBase.h.
References id.
{ return id  < other.id; }
Dimension & Dimension::time_static () [static]
Shortcut to the time Dimension, same as 'Dimension("time")', but spares the parsing of a string.
This method should be used instead of the static "time" member when used during initialization of static variables since it assures the correct order of initialization.
Definition at line 29 of file MappingBase.cc.
References time.
{
  //use "construct-on-first-use" idiom to ensure correct order of
  //static initialization
  static Dimension* time = new Dimension("time");
  return *time;
}
The documentation for this class was generated from the following files:
src/base/phyLayer/MappingBase.h
src/base/phyLayer/MappingBase.cc