MiXiM: BaseModule Class Reference
BaseModule Class Reference
[baseModules - base module classes of MiXiM]
Base class for all simple modules of a host.
#include <BaseModule.h>
Inherited by ArpHost, BaseArp, BaseBattery, BatteryAccess, BatteryStats, phyPER, SimpleMacLayer, SimpleNetwLayer, and TestApplication.
Public Member Functions
BaseModule (unsigned stacksize)
virtual void initialize (int)
Basic initialization for all modules.
virtual int numInitStages () const
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule * getNode () const
Get a reference to the local node module.
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Called by the signaling mechanism whenever a change of a category occurs to which we have subscribed. In this base class just handle the host state switching and some debug notifications.
Protected Member Functions
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule * findHost (void)
Function to get a pointer to the host module.
const cModule * findHost (void) const
Protected Attributes
bool debug
Debug switch for all other modules.
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state. If not explicitly set this module has to capture changes in the host state.
Static Protected Attributes
static const simsignalwrap_t catHostStateSignal = simsignalwrap_t(MIXIM_SIGNAL_HOSTSTATE_NAME)
Stores the category of the HostState.
Private Member Functions
BaseModule (const BaseModule &)
Function to get the logging name of id.
BaseModule & operator= (const BaseModule &)
Assignment operator is not allowed.
Detailed Description
Base class for all simple modules of a host.
This method raises an error if the host state changes to something else than ACTIVE. Therefore that a sub-classing module can be used in a simulation where the host state can change it has to override that method which forces the author to make sure the module reacts well to host state changes. Alternatively one can also set a "notAffectedByHostState" parameter of the module to true.
The base module additionally provides a function findHost which returns a pointer to the host module and a function hostIndex to return the index of the host module. The latter one correspondes to the index shown in tkenv and comes in very handy for testing and debugging using tkenv. It is used e.g. in all the 'print' macros used for debugging.
There will never be a stand-alone BaseModule module.
Note: most modules wont derive from BaseModule directly but from its sub class "BatteryAccess" which extends BaseModule by several methods for accessing the battery module.
See also:
BatteryAccess
Author:
Steffen Sroka
Andreas Koepke
Definition at line 73 of file BaseModule.h.
Constructor & Destructor Documentation
BaseModule::BaseModule (const BaseModule &) [private]
Function to get the logging name of id.
Copy constructor is not allowed.
Member Function Documentation
void BaseModule::handleHostState (const HostState & state) [protected, virtual]
Called whenever the hosts state changes.
Default implementation of this method throws an error whenever the host state changes and the "notAffectedbyHostState" variable is not explicitly set. This is because every module of a host has to make sure to react well to changes in the host state. Or it has to explicitly set its parameter "notAffectedbyHostState" to true.
Reimplemented in BurstApplLayerBattery, PhyLayerBattery, PhyLayerUWBIR, and SimpleBattery.
Definition at line 73 of file BaseModule.cc.
References HostState::get(), and notAffectedByHostState.
Referenced by receiveSignal().
{
  if(notAffectedByHostState)
    return;
  if(state.get() != HostState::ACTIVE) {
    error("Hosts state changed to something else than active which"
        " is not handled by this module. Either handle this state"
        " correctly or if this module really isn't affected by the"
        " hosts state set the parameter \"notAffectedByHostState\""
        " of this module to true.");
  }
}
void BaseModule::initialize (int stage) [virtual]
Basic initialization for all modules.
Subscription should be in stage==0, and firing notifications in stage==1 or later.
NOTE: You have to call this in the initialize() function of the inherited class!
Reimplemented in ChannelAccess, BaseApplLayer, BaseArp, BaseLayer, BaseMacLayer, BaseMobility, BaseNetwLayer, TestApplLayer, BasePhyLayer, BurstApplLayer, BurstApplLayerBattery, SensorApplLayer, TestApplication, TrafficGen, AlohaMacLayer, BMacLayer, csma, CSMA802154, CSMAMacLayer, LMacLayer, Mac80211, Mac80211MultiChannel, UWBIRMac, ANSimMobility, BonnMotionMobility, CircleMobility, ConstSpeedMobility, LinearMobility, LineSegmentsMobilityBase, MassMobility, MoBANLocal, RectangleMobility, TractorMobility, TurtleMobility, AdaptiveProbabilisticBroadcast, ArpHost, DummyRoute, Flood, ProbabilisticBroadcast, WiseRoute, PhyLayerBattery, PhyLayerUWBIR, BatteryStats, SimpleBattery, Aggregation, phyPER, SamplePhyLayer, SimpleMacLayer, SimpleNetwLayer, and NetworkStackTrafficGen.
Definition at line 51 of file BaseModule.cc.
References catHostStateSignal, debug, findHost(), and notAffectedByHostState.
{
    if (stage == 0) {
      notAffectedByHostState =  hasPar("notAffectedByHostState")
                 && par("notAffectedByHostState").boolValue();
        hasPar("debug") ? debug = par("debug").boolValue() : debug = true;
        findHost()->subscribe(catHostStateSignal, this);
    }
}
std::string BaseModule::logName (void) const
Function to get the logging name of the host.
The logging name is the ned module name of the host (unless the host ned variable loggingName is specified). It can be used for logging messages to simplify debugging in TKEnv.
This function returns the logging name of the module with the specified id. It can be used for logging messages to simplify debugging in TKEnv.
Only supports ids from simple module derived from the BaseModule or the nic compound module id.
Parameters:
id Id of the module for the desired logging name
Returns:
logging name of module id or NULL if not found
See also:
logName
Definition at line 131 of file BaseModule.cc.
References findHost().
{
  std::ostringstream ost;
  if (hasPar("logName")) // let modules override
  {
    ost << par("logName").stringValue();
  }
  else
  {
    const cModule *const parent = findHost();
    parent->hasPar("logName") ?
      ost << parent->par("logName").stringValue() : ost << parent->getName();
    ost << "[" << parent->getIndex() << "]";
  }
  return ost.str();
}
virtual int BaseModule::numInitStages () const [inline, virtual]
Divide initialization into two stages.
In the first stage (stage==0), modules subscribe to notification. The first notifications (e.g. about the initial values of some variables such as RadioState) should take place earliest in the second stage (stage==1), when everyone interested in them has already subscribed. Further one should try to keep calls to other modules out of stage 0 to assure that the other module had at least once the chance to initialize itself in stage 0.
Definition at line 141 of file BaseModule.h.
{
      return 2;
    }
void BaseModule::switchHostState (HostState::States state) [protected]
Switches the host to the passed state.
If the hosts state is switched to anything else than "ACTIVE" every module of the host has to handle this explicitly (see method "handleHostState()")!
Definition at line 87 of file BaseModule.cc.
References catHostStateSignal.
{
  HostState hostState(state);
  emit(catHostStateSignal, &hostState);
}
The documentation for this class was generated from the following files:
src/base/modules/BaseModule.h
src/base/modules/BaseModule.cc