MiXiM: DimensionSet Class Reference
DimensionSet Class Reference
[mapping - classes representing mathematical mappings]
Represents a set of dimensions which is used to define over which dimensions a mapping is defined (the domain of the mapping).
#include <MappingBase.h>
Public Types
typedef _Base::value_type value_type
typedef _Base::iterator iterator
typedef _Base::reverse_iterator reverse_iterator
typedef _Base::reverse_iterator const_reverse_iterator
typedef _Base::const_iterator const_iterator
typedef _Base::size_type size_type
typedef _Base::const_reference const_reference
Public Member Functions
DimensionSet ()
Default constructor creates an empty DimensionSet.
DimensionSet (const DimensionSet &o)
Copy constructor.
DimensionSet & operator= (DimensionSet const &copy)
DimensionSet assignment operator.
void swap (DimensionSet &s)
Swaps data with another DimensionSet.
DimensionSet (const DimensionSet::value_type &d)
Creates a new DimensionSet with the passed Dimension as initial Dimension.
DimensionSet (const DimensionSet::value_type &d1, const DimensionSet::value_type &d2)
Creates a new DimensionSet with the passed Dimensions as initial Dimensions (convenience method).
DimensionSet (const DimensionSet::value_type &d1, const DimensionSet::value_type &d2, const DimensionSet::value_type &d3)
Creates a new DimensionSet with the passed Dimensions as initial Dimensions (convenience method).
bool isSubSet (const DimensionSet &other) const
Returns true if the passed DimensionSet is a subset of this DimensionSet.
bool isRealSubSet (const DimensionSet &other) const
Returns true if the passed DimensionSet is a real subset of this DimensionSet.
void addDimension (const DimensionSet::value_type &d)
Adds the passed dimension to the DimensionSet.
bool hasDimension (const DimensionSet::value_type &d) const
Returns true if the passed Dimension is inside this DimensionSet.
bool operator== (const DimensionSet &o) const
Returns true if the dimensions of both sets are equal.
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
const_iterator find (const value_type &__x) const
size_type size () const
Returns the size of the DimensionSet.
template<typename _InputIterator >
void insert (_InputIterator __first, _InputIterator __last)
A template function that attempts to insert a range of elements.
iterator insert (const_iterator __position, const value_type &__x)
Attempts to insert an element into the DimensionSet.
bool empty () const
Returns true if the DimensionSet is empty.
Static Public Attributes
static const DimensionSet timeDomain
Shortcut to a DimensionSet which only contains time.
static const DimensionSet timeFreqDomain
Shortcut to a DimensionSet which contains time and frequency.
Protected Types
typedef std::set< Dimension > _Base
Protected Attributes
_Base Storage
Detailed Description
Represents a set of dimensions which is used to define over which dimensions a mapping is defined (the domain of the mapping).
This class actually public extends from std::set<Dimension>. So any method provided by std::set can be also used.
The dimensions are stored ordered by their ids.
Note: Unlike Arguments and Mappings, a DimensionSet does not contain "time" as dimension per default. You'll have to add it like any other dimension.
Author:
Karl Wessel
Definition at line 178 of file MappingBase.h.
Member Function Documentation
iterator DimensionSet::insert (const_iterator __position, const value_type & __x) [inline]
Attempts to insert an element into the DimensionSet.
Parameters:
position An iterator that serves as a hint as to where the element should be inserted.
x Element to be inserted.
Returns:
An iterator that points to the element with key of x (may or may not be the element passed in).
This function is not concerned about whether the insertion took place, and thus does not return a boolean like the single-argument insert() does. Note that the first parameter is only a hint and can potentially improve the performance of the insertion process. A bad hint would cause no gains in efficiency.
For more on hinting, see: http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt07ch17.html
Insertion requires logarithmic time (if the hint is not taken).
Definition at line 394 of file MappingBase.h.
{
    return Storage.insert(__position, __x);
  }
template<typename _InputIterator > void DimensionSet::insert (_InputIterator __first, _InputIterator __last) [inline]
A template function that attempts to insert a range of elements.
Parameters:
first Iterator pointing to the start of the range to be inserted.
last Iterator pointing to the end of the range.
Complexity similar to that of the range constructor.
Definition at line 371 of file MappingBase.h.
Referenced by Argument::getDimensions().
  { Storage.insert(__first, __last); }
bool DimensionSet::isRealSubSet (const DimensionSet & other) const [inline]
Returns true if the passed DimensionSet is a real subset of this DimensionSet.
A DimensionSet is a real subset of this DimensionSet if every Dimension of the passed DimensionSet is defined in this DimensionSet and there is at least one Dimensions in this set which isn't in the other set.
Definition at line 288 of file MappingBase.h.
References size().
{
    if(size() <= other.size())
      return false;
    return std::includes(begin(), end(), other.begin(), other.end());
  }
bool DimensionSet::isSubSet (const DimensionSet & other) const [inline]
Returns true if the passed DimensionSet is a subset of this DimensionSet.
A DimensionSet is a subset of this DimensionSet if every Dimension of the passed DimensionSet is defined in this DimensionSet.
Definition at line 272 of file MappingBase.h.
Referenced by MappingUtils::findMax(), MappingUtils::findMin(), and SimpleConstMappingIterator::SimpleConstMappingIterator().
{
    if(Storage.size() < other.Storage.size())
      return false;
    return std::includes(Storage.begin(), Storage.end(), other.Storage.begin(), other.Storage.end());
  }
DimensionSet& DimensionSet::operator= (DimensionSet const & copy) [inline]
DimensionSet assignment operator.
Parameters:
copy A DimensionSet of identical element and allocator types.
All the elements of copy are copied.
Definition at line 215 of file MappingBase.h.
  {
    DimensionSet tmp(copy); // All resource all allocation happens here.
                              // If this fails the copy will throw an exception
                              // and 'this' object is unaffected by the exception.
    swap(tmp);
    return *this;
  }
void DimensionSet::swap (DimensionSet & s) [inline]
Swaps data with another DimensionSet.
Parameters:
s A DimensionSet of the same element and allocator types.
This exchanges the elements between two DimensionSet's in constant time. Note that the global std::swap() function is specialized such that std::swap(s1,s2) will feed to this function.
Definition at line 232 of file MappingBase.h.
Referenced by ConstMapping::swap().
  {
    // X::swap(s); // swap the base class members
    /* Swap all D members */
    std::swap(Storage, s.Storage);
  }
The documentation for this class was generated from the following files:
src/base/phyLayer/MappingBase.h
src/base/phyLayer/MappingBase.cc