MiXiM: ChannelInfo Class Reference
ChannelInfo Class Reference
[phyLayer - physical layer modules]
This class is used by the BasePhyLayer to keep track of the AirFrames on the channel.
#include <ChannelInfo.h>
Classes
class BaseIntersectionIterator
Iterator for every intersection of a specific interval in a AirFrameMatrix.
struct c_min_start_time_fctr
Public Types
typedef AirFrame * airframe_ptr_t
typedef std::list< airframe_ptr_t > AirFrameVector
Type for a container of AirFrames.
Public Member Functions
void addAirFrame (airframe_ptr_t a, simtime_t_cref startTime)
Tells the ChannelInfo that an AirFrame has started.
simtime_t removeAirFrame (airframe_ptr_t a, simtime_t_cref returnTimeIfEmpty=-1)
Tells the ChannelInfo that an AirFrame is over.
void getAirFrames (simtime_t_cref from, simtime_t_cref to, AirFrameVector &out) const
Fills the passed AirFrameVector reference with the AirFrames which intersect with the given time interval.
simtime_t getEarliestInfoPoint (simtime_t_cref returnTimeIfEmpty=-1) const
Returns the current time-point from that information concerning AirFrames is needed to be stored.
void startRecording (simtime_t_cref start)
Tells ChannelInfo to keep from now on all channel information until the passed time in history.
void stopRecording ()
Tells ChannelInfo to stop recording Information from now on.
bool isRecording () const
Returns true if ChannelInfo is currently recording.
bool isChannelEmpty () const
Returns true if there are currently no active or inactive AirFrames on the channel.
Protected Types
typedef std::map< simtime_t,
std::multimap< simtime_t,
airframe_ptr_t > > AirFrameMatrix
typedef
BaseIntersectionIterator
< const AirFrameMatrix,
AirFrameMatrix::const_iterator,
AirFrameMatrix::mapped_type::const_iterator > const_iterator
Type for a const-iterator over an AirFrame interval matrix.
typedef
BaseIntersectionIterator
< AirFrameMatrix,
AirFrameMatrix::iterator,
AirFrameMatrix::mapped_type::iterator > iterator
Type for a iterator over an AirFrame interval matrix.
typedef std::map< long, simtime_t > AirFrameStartMap
Type for a map of AirFrame pointers to their start time.
Protected Member Functions
const_iterator end () const
iterator end ()
void erase (const iterator &__position)
Erases an element from a AirFrameMatrix.
void assertNoIntersections () const
Asserts that every inactive AirFrame is still intersecting with at least one active airframe or with the current record start time.
void addToInactives (airframe_ptr_t a, simtime_t_cref startTime, simtime_t_cref endTime)
Moves a previously active AirFrame to the inactive AirFrames.
simtime_t findEarliestInfoPoint (simtime_t_cref returnTimeIfEmpty=-1) const
Returns the start time of the odlest AirFrame on the channel.
void checkAndCleanInterval (simtime_t_cref startTime, simtime_t_cref endTime)
Checks if any information inside the passed interval can be discarded.
bool canDiscardInterval (simtime_t_cref startTime, simtime_t_cref endTime)
Returns true if all information inside the passed interval can be deleted.
void checkAndCleanFrom (simtime_t_cref start)
Checks if any information up from the passed start time can be discarded.
Static Protected Member Functions
static void getIntersections (const AirFrameMatrix &airFrames, simtime_t_cref from, simtime_t_cref to, AirFrameVector &outVector)
Returns every AirFrame of an AirFrameMatrix which intersect with a given interval.
static bool isIntersecting (const AirFrameMatrix &airFrames, simtime_t_cref from, simtime_t_cref to)
Returns true if there is at least one AirFrame in the passed AirFrameMatrix which intersect with the given interval.
static void deleteAirFrame (AirFrameMatrix &airFrames, airframe_ptr_t a, simtime_t_cref startTime, simtime_t_cref endTime)
Deletes an AirFrame from an AirFrameMatrix.
Protected Attributes
AirFrameMatrix activeAirFrames
Stores the currently active AirFrames.
AirFrameMatrix inactiveAirFrames
Stores inactive AirFrames.
AirFrameStartMap airFrameStarts
Stores the start time of every AirFrame.
simtime_t recordStartTime
Stores a point in history up to which we need to keep all channel information stored.
Static Protected Attributes
static const const_iterator cConstItEnd
The end iterator for the matrix.
static const iterator cItEnd
The end iterator for the matrix.
Detailed Description
This class is used by the BasePhyLayer to keep track of the AirFrames on the channel.
ChannelInfo is able to return every AirFrame which intersects with a specified interval. This is mainly used to get the noise for a received signal.
ChannelInfo is a passive class meaning the user has to tell it when a new AirFrame starts and an existing ends.
Once an AirFrame has been added to the ChannelInfo the ChannelInfo holds the ownership of this AirFrame even if the AirFrame is removed again from the ChannelInfo. This is necessary because the ChannelInfo has to be able to store also the AirFrames which are over but still intersect with an currently running AirFrame.
Note: ChannelInfo assumes that the AirFrames are added and removed chronologically. This means every time you add an AirFrame with a specific start time ChannelInfo assumes that start time as the current time and assumes that every following action happens after that moment. The same goes for "removeAirFrame". When removing an AirFrames, ChannelInfo assumes the start time plus the duration of the AirFrame as the current time. This also affects "getAirFrames" in the way that you may only ask for intervals which lie before the "current time" of ChannelInfo.
A state-machine-diagram for Radio, RadioStateAnalogueModel and ChannelInfo showing how they work together under control of BasePhyLayer as well as some documentation on how RadioStateAnalogueModel works is available in phyLayer - physical layer modules.
Definition at line 45 of file ChannelInfo.h.
Member Typedef Documentation
typedef AirFrame* ChannelInfo::airframe_ptr_t
The stored air frame pointer type
Definition at line 48 of file ChannelInfo.h.
typedef std::map<simtime_t, std::multimap<simtime_t, airframe_ptr_t> > ChannelInfo::AirFrameMatrix [protected]
The AirFrames are stored in a Matrix with start- and end time as dimensions.
Definition at line 54 of file ChannelInfo.h.
typedef std::list<airframe_ptr_t> ChannelInfo::AirFrameVector
Type for a container of AirFrames.
Used as out type for "getAirFrames" method.
Definition at line 330 of file ChannelInfo.h.
Member Function Documentation
void ChannelInfo::addAirFrame (airframe_ptr_t a, simtime_t_cref startTime)
Tells the ChannelInfo that an AirFrame has started.
From this point ChannelInfo gets the ownership of the AirFrame.
parameter startTime holds the time the receiving of the AirFrame has started in seconds.
Definition at line 9 of file ChannelInfo.cc.
References activeAirFrames, airFrameStarts, and isChannelEmpty().
Referenced by BasePhyLayer::handleAirFrameStartReceive().
{
  assert(airFrameStarts.count(frame->getTreeId()) == 0);
  //calculate endTime of AirFrame
  simtime_t endTime = startTime + frame->getDuration();
  AirFrameMatrix::iterator pos = activeAirFrames.lower_bound(endTime);
  if(pos == activeAirFrames.end() || (activeAirFrames.key_comp()(endTime, pos->first))) {
      // key does not exists
    pos = activeAirFrames.insert(pos, std::make_pair(endTime, AirFrameMatrix::mapped_type()));
  }
  pos->second.insert(std::make_pair(startTime, frame));
  //add to start time map
  airFrameStarts[frame->getTreeId()] = startTime;
  assert(!isChannelEmpty());
}
void ChannelInfo::addToInactives (airframe_ptr_t a, simtime_t_cref startTime, simtime_t_cref endTime) [protected]
Moves a previously active AirFrame to the inactive AirFrames.
This methods checks if there are some inactive AirFrames which can be deleted because the AirFrame to in-activate was the last one they intersected with. It also checks if the AirFrame to in-activate still intersect with at least one active AirFrame before it is moved to inactive AirFrames.
Definition at line 29 of file ChannelInfo.cc.
References airFrameStarts, canDiscardInterval(), checkAndCleanInterval(), and inactiveAirFrames.
Referenced by removeAirFrame().
{
  // At first, check if some inactive AirFrames can be removed because the
  // AirFrame to in-activate was the last one they intersected with.
  checkAndCleanInterval(startTime, endTime);
  if(!canDiscardInterval(startTime, endTime)) {
    AirFrameMatrix::iterator pos = inactiveAirFrames.lower_bound(endTime);
    if(pos == inactiveAirFrames.end() || (inactiveAirFrames.key_comp()(endTime, pos->first))) {
        // key does not exists
      pos = inactiveAirFrames.insert(pos, std::make_pair(endTime, AirFrameMatrix::mapped_type()));
    }
    pos->second.insert(std::make_pair(startTime, frame));
  }
  else {
    airFrameStarts.erase(frame->getTreeId());
    delete frame;
  }
}
bool ChannelInfo::canDiscardInterval (simtime_t_cref startTime, simtime_t_cref endTime) [protected]
Returns true if all information inside the passed interval can be deleted.
For example this method is used to check if information for the duration of an AirFrame is needed anymore and if not the AirFrame is deleted.
Parameters:
startTime The start time of the interval (e.g. AirFrame start)
endTime The end time of the interval (e.g. AirFrame end)
Returns:
returns true if any information for the passed interval can be discarded.
Definition at line 147 of file ChannelInfo.cc.
References activeAirFrames, isIntersecting(), and recordStartTime.
Referenced by addToInactives(), and checkAndCleanInterval().
{
  assert(recordStartTime >= 0 || recordStartTime == -1);
  // only if it ends before the point in time we started recording or if
  // we aren't recording at all and it does not intersect with any active one
  // anymore this AirFrame can be deleted
  return (recordStartTime > endTime || recordStartTime == -1)
       && !isIntersecting(activeAirFrames, startTime, endTime);
}
void ChannelInfo::checkAndCleanFrom (simtime_t_cref start) [inline, protected]
Checks if any information up from the passed start time can be discarded.
Parameters:
startTime The start of the interval to check
Definition at line 413 of file ChannelInfo.h.
References checkAndCleanInterval(), and inactiveAirFrames.
Referenced by stopRecording().
{
    //nothing to do
    if(inactiveAirFrames.empty())
      return;
    //take last ended inactive airframe as end of interval
    checkAndCleanInterval(start, inactiveAirFrames.rbegin()->first);
  }
void ChannelInfo::checkAndCleanInterval (simtime_t_cref startTime, simtime_t_cref endTime) [protected]
Checks if any information inside the passed interval can be discarded.
This method should be called every time the information for a certain interval changes (AirFrame is removed or record time changed).
Parameters:
startTime The start of the interval to check
endTime The end of the interval to check
Definition at line 159 of file ChannelInfo.cc.
References airFrameStarts, canDiscardInterval(), end(), erase(), and inactiveAirFrames.
Referenced by addToInactives(), checkAndCleanFrom(), and startRecording().
{
  // get through inactive AirFrame which intersected with the passed interval
  iterator itInactiveFrames(&inactiveAirFrames, startTime, endTime);
  iterator itEnd = end();
  for (; itInactiveFrames != itEnd;) {
    airframe_ptr_t pInactiveFrame = itInactiveFrames->second;
    simtime_t      currentEnd     = itInactiveFrames->first + pInactiveFrame->getDuration();
    if(canDiscardInterval(itInactiveFrames->first, currentEnd)) {
      erase(itInactiveFrames++);
      airFrameStarts.erase(pInactiveFrame->getTreeId());
      delete pInactiveFrame;
      continue;
    }
    ++itInactiveFrames;
  }
}
iterator ChannelInfo::end () [inline, protected]
Returns a read/write iterator that points one past the last pair in the AirFrameMatrix. Iteration is done in ascending order according to the end, and start time.
Definition at line 272 of file ChannelInfo.h.
References cItEnd.
                 {
    return cItEnd;
  }
const_iterator ChannelInfo::end () const [inline, protected]
Returns a read-only (constant) iterator that points one past the last pair in the AirFrameMatrix. Iteration is done in ascending order according to the end, and start time.
Definition at line 256 of file ChannelInfo.h.
References cConstItEnd.
Referenced by checkAndCleanInterval().
{
    return cConstItEnd;
  }
void ChannelInfo::erase (const iterator & __position) [inline, protected]
Erases an element from a AirFrameMatrix.
Parameters:
position An iterator pointing to the element to be erased.
This function erases an element, pointed to by the given iterator, from a AirFrameMatrix. Note that this function only erases the element, and that if the element is itself a pointer, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Definition at line 286 of file ChannelInfo.h.
References ChannelInfo::BaseIntersectionIterator< C, ItMatrix, ItSubMatrix >::endIt, ChannelInfo::BaseIntersectionIterator< C, ItMatrix, ItSubMatrix >::intervals, and ChannelInfo::BaseIntersectionIterator< C, ItMatrix, ItSubMatrix >::startIt.
Referenced by checkAndCleanInterval().
{
    assert(__position.endIt   != __position.intervals->end());
    assert(__position.startIt != __position.startItEnd);
    //erase AirFrame from list
    __position.endIt->second.erase(__position.startIt);
    //check if we deleted the only entry in the list
    if(__position.endIt->second.empty()) {
      __position.intervals->erase(__position.endIt); //delete list from map
    }
  }
void ChannelInfo::getAirFrames (simtime_t_cref from, simtime_t_cref to, AirFrameVector & out) const
Fills the passed AirFrameVector reference with the AirFrames which intersect with the given time interval.
Note: Completeness of the list of AirFrames for specific interval can only be assured if start and end point of the interval lies inside the duration of at least one currently active AirFrame. An AirFrame is called active if it has been added but not yet removed from ChannelInfo.
Definition at line 197 of file ChannelInfo.cc.
References activeAirFrames, getIntersections(), and inactiveAirFrames.
Referenced by BasePhyLayer::getChannelInfo(), and BasePhyLayer::~BasePhyLayer().
{
  //check for intersecting inactive AirFrames
  getIntersections(inactiveAirFrames, from, to, out);
  //check for intersecting active AirFrames
  getIntersections(activeAirFrames, from, to, out);
}
void ChannelInfo::getIntersections (const AirFrameMatrix & airFrames, simtime_t_cref from, simtime_t_cref to, AirFrameVector & outVector) [static, protected]
Returns every AirFrame of an AirFrameMatrix which intersect with a given interval.
The intersecting AirFrames are stored in the AirFrameVector reference passed as parameter.
Definition at line 187 of file ChannelInfo.cc.
References cConstItEnd.
Referenced by getAirFrames().
{
  const_iterator itEnd = cConstItEnd;
  for (const_iterator it(&airFrames, from, to); it != itEnd; ++it) {
    outVector.push_back(it->second);
  }
}
bool ChannelInfo::isRecording () const [inline]
Returns true if ChannelInfo is currently recording.
Returns:
true if ChannelInfo is recording
Definition at line 517 of file ChannelInfo.h.
References recordStartTime.
Referenced by BasePhyLayer::handleChannelSenseRequest(), and BasePhyLayer::sendControlMsgToMac().
  {
    return recordStartTime > -1;
  }
simtime_t ChannelInfo::removeAirFrame (airframe_ptr_t a, simtime_t_cref returnTimeIfEmpty = -1)
Tells the ChannelInfo that an AirFrame is over.
This does not mean that it loses ownership of the AirFrame.
Returns:
The current time-point from on which information concerning AirFrames is needed to be stored.
Definition at line 69 of file ChannelInfo.cc.
References activeAirFrames, addToInactives(), airFrameStarts, deleteAirFrame(), findEarliestInfoPoint(), and isChannelEmpty().
Referenced by BasePhyLayer::handleAirFrameEndReceive().
{
  assert(airFrameStarts.count(frame->getTreeId()) > 0);
  //get start of AirFrame
  simtime_t_cref startTime = airFrameStarts[frame->getTreeId()];
  //calculate end time
  simtime_t      endTime   = startTime + frame->getDuration();
  //remove this AirFrame from active AirFrames
  deleteAirFrame(activeAirFrames, frame, startTime, endTime);
  //add to inactive AirFrames
  addToInactives(frame, startTime, endTime);
  // Now check, whether the earliest time-point we need to store information
  // for might have moved on in time, since an AirFrame has been deleted.
  if(isChannelEmpty()) {
    return returnTimeIfEmpty;
  }
  return findEarliestInfoPoint(returnTimeIfEmpty);
}
void ChannelInfo::startRecording (simtime_t_cref start) [inline]
Tells ChannelInfo to keep from now on all channel information until the passed time in history.
The passed start-time should be the current simulation time, otherwise ChannelInfo can't assure that it hasn't already thrown away some information for that passed time period.
Subsequent calls to this method will update the recording start time and information from old start times is thrown away.
Parameters:
start The point in time from which to keep all channel information stored.
Definition at line 487 of file ChannelInfo.h.
References checkAndCleanInterval(), and recordStartTime.
Referenced by BasePhyLayer::handleChannelSenseRequest().
  {
    // clean up until old record start
    if(recordStartTime > -1) {
      recordStartTime = start;
      checkAndCleanInterval(0, recordStartTime);
    } else {
      recordStartTime = start;
    }
  }
void ChannelInfo::stopRecording () [inline]
Tells ChannelInfo to stop recording Information from now on.
Its up to ChannelInfo to decide when to actually throw away the information it doesn't need to store anymore now.
Definition at line 504 of file ChannelInfo.h.
References checkAndCleanFrom(), and recordStartTime.
Referenced by BasePhyLayer::sendControlMsgToMac().
  {
    if(recordStartTime > -1) {
      simtime_t old = recordStartTime;
      recordStartTime = -1;
      checkAndCleanFrom(old);
    }
  }
Member Data Documentation
AirFrameMatrix ChannelInfo::activeAirFrames [protected]
Stores the currently active AirFrames.
This means every AirFrame which was added but not yet removed.
Definition at line 304 of file ChannelInfo.h.
Referenced by addAirFrame(), assertNoIntersections(), canDiscardInterval(), findEarliestInfoPoint(), getAirFrames(), isChannelEmpty(), and removeAirFrame().
AirFrameMatrix ChannelInfo::inactiveAirFrames [protected]
Stores inactive AirFrames.
This means every AirFrame which has been already removed but still is needed because it intersect with one or more active AirFrames.
Definition at line 312 of file ChannelInfo.h.
Referenced by addToInactives(), assertNoIntersections(), checkAndCleanFrom(), checkAndCleanInterval(), findEarliestInfoPoint(), and getAirFrames().
The documentation for this class was generated from the following files:
src/base/phyLayer/ChannelInfo.h
src/base/phyLayer/ChannelInfo.cc