MiXiM: ConstMappingIterator Class Reference
ConstMappingIterator Class Reference
[mapping - classes representing mathematical mappings]
Defines an const iterator for a ConstMapping which is able to iterate over the Mapping.
#include <MappingBase.h>
Inherited by BaseFilteredIterator< ConstMappingIterator >, MappingIterator, RSAMConstMappingIterator, and SimpleConstMappingIterator.
Public Types
typedef Argument::mapped_type argument_value_t
typedef Argument::mapped_type_cref argument_value_cref_t
Public Member Functions
ConstMappingIterator (const ConstMappingIterator &)
Copy constructor.
ConstMappingIterator & operator= (const ConstMappingIterator &)
ConstMappingIterator assignment operator.
void swap (ConstMappingIterator &)
Swaps data with another ConstMappingIterator.
virtual const Argument & getNextPosition () const =0
Returns the position the next call to "next()" of this Iterator would iterate to.
virtual void jumpTo (const Argument &pos)=0
Lets the iterator point to the passed position.
virtual void jumpToBegin ()=0
Lets the iterator point to the begin of the mapping.
virtual void iterateTo (const Argument &pos)=0
Iterates to the specified position. This method should be used if the new position is near the current position. Furthermore the new position has to be compared bigger than the old position.
virtual void next ()=0
Iterates to the next position of the Mapping.
virtual bool inRange () const =0
Returns true if the current position of the iterator is in range of the function.
virtual bool hasNext () const =0
Returns true if the iterator has a next value it can iterate to on a call to "next()".
virtual const Argument & getPosition () const =0
Returns the current position of the iterator.
virtual argument_value_t getValue () const =0
Returns the value of the Mapping at the current position.
Detailed Description
Defines an const iterator for a ConstMapping which is able to iterate over the Mapping.
Iterators provide a fast way to iterate over every "entry" or important position of a Mapping. They also provide constant complexity for accessing the Mapping at the position of the Iterator.
Every implementation of an mapping-Iterator provides the same ordering when iterating over a Mapping. This is that, if the iterator is increased, the position of the entry it points to has to be also "increased". Which means that the new position has to be compared bigger than the previous position (see class Argument for comparison of positions).
"Const" means that you can not change the values of the underlying Mapping with this iterator.
Author:
Karl Wessel
Definition at line 708 of file MappingBase.h.
Member Function Documentation
virtual argument_value_t ConstMappingIterator::getValue () const [pure virtual]
Returns the value of the Mapping at the current position.
The complexity of this method should be constant for every implementation.
Implemented in SimpleConstMappingIterator, TimeMappingIterator< Interpolator >, LinearIntplMappingIterator, ConstMappingIteratorWrapper, MultiDimMappingIterator< Interpolator >, RSAMConstMappingIterator, and MultiDimMappingIterator< Linear >.
Referenced by SNRThresholdDecider::checkIfAboveThreshold(), Decider80211MultiChannel::checkIfSignalOk(), Decider80211::checkIfSignalOk(), UWBIRIEEE802154APathlossModel::filterSignal(), MappingUtils::findMax(), MappingUtils::findMin(), MultiDimMappingIterator< Linear >::getValue(), ThresholdDecider::handleSignalOver(), ConstMapping::print(), and Decider802154Narrow::processSignalEnd().
virtual bool ConstMappingIterator::inRange () const [pure virtual]
Returns true if the current position of the iterator is in range of the function.
This method should be used as end-condition when iterating over the function with the "next()" method.
Implemented in SimpleConstMappingIterator, TimeMappingIterator< Interpolator >, LinearIntplMappingIterator, ConstMappingIteratorWrapper, MultiDimMappingIterator< Interpolator >, RSAMConstMappingIterator, and MultiDimMappingIterator< Linear >.
Referenced by UWBIRIEEE802154APathlossModel::filterSignal(), MappingUtils::findMax(), MappingUtils::findMin(), ThresholdDecider::handleSignalOver(), MultiDimMappingIterator< Linear >::inRange(), and ConstMapping::print().
virtual void ConstMappingIterator::jumpTo (const Argument & pos) [pure virtual]
Lets the iterator point to the passed position.
The passed new position can be at arbitrary places.
Implemented in SimpleConstMappingIterator, TimeMappingIterator< Interpolator >, LinearIntplMappingIterator, ConstMappingIteratorWrapper, MultiDimMappingIterator< Interpolator >, RSAMConstMappingIterator, and MultiDimMappingIterator< Linear >.
Referenced by MultiDimMappingIterator< Linear >::jumpTo(), RSAMConstMappingIterator::jumpToBegin(), and MultiDimMappingIterator< Linear >::updateSubIterator().
virtual void ConstMappingIterator::jumpToBegin () [pure virtual]
Lets the iterator point to the begin of the mapping.
The beginning of the mapping depends on the implementation. With an implementation based on a number of key-entries, this could be the key entry with the smallest position (see class Argument for ordering of positions).
Implemented in SimpleConstMappingIterator, TimeMappingIterator< Interpolator >, LinearIntplMappingIterator, ConstMappingIteratorWrapper, MultiDimMappingIterator< Interpolator >, RSAMConstMappingIterator, and MultiDimMappingIterator< Linear >.
Referenced by MultiDimMappingIterator< Linear >::updateSubIterator().
virtual void ConstMappingIterator::next () [pure virtual]
Iterates to the next position of the Mapping.
The next position depends on the implementation of the Mapping. With an implementation based on a number of key-entries this probably would be the next bigger key-entry.
Implemented in SimpleConstMappingIterator, TimeMappingIterator< Interpolator >, LinearIntplMappingIterator, ConstMappingIteratorWrapper, MultiDimMappingIterator< Interpolator >, RSAMConstMappingIterator, and MultiDimMappingIterator< Linear >.
Referenced by SNRThresholdDecider::canAnswerCSR(), SNRThresholdDecider::checkIfAboveThreshold(), Decider80211MultiChannel::checkIfSignalOk(), Decider80211::checkIfSignalOk(), UWBIRIEEE802154APathlossModel::filterSignal(), MappingUtils::findMax(), MappingUtils::findMin(), ThresholdDecider::handleSignalOver(), MultiDimMappingIterator< Linear >::next(), ConstMapping::print(), and Decider802154Narrow::processSignalEnd().
ConstMappingIterator& ConstMappingIterator::operator= (const ConstMappingIterator &) [inline]
ConstMappingIterator assignment operator.
Parameters:
copy A ConstMappingIterator of identical element and allocator types.
All the elements of copy are copied.
Reimplemented in SimpleConstMappingIterator, LinearIntplMappingIterator, ConstMappingIteratorWrapper, MultiDimMappingIterator< Interpolator >, ConcatConstMappingIterator, and RSAMConstMappingIterator.
Definition at line 727 of file MappingBase.h.
{return *this;}
void ConstMappingIterator::swap (ConstMappingIterator &) [inline]
Swaps data with another ConstMappingIterator.
Parameters:
s A ConstMappingIterator of the same element and allocator types.
This exchanges the elements between two ConstMappingIterator's in constant time. Note that the global std::swap() function is specialized such that std::swap(s1,s2) will feed to this function.
Definition at line 737 of file MappingBase.h.
{}
The documentation for this class was generated from the following file:
src/base/phyLayer/MappingBase.h