MiXiM: BaseWorldUtility Class Reference
BaseWorldUtility Class Reference
[baseModules - base module classes of MiXiM]
Provides information and utility methods for the whole simulation.
#include <BaseWorldUtility.h>
Inherited by WorldUtilityStats.
Public Member Functions
virtual void initialize (int stage)
const Coord * getPgs ()
Returns the playgroundSize.
bool useTorus ()
Returns true if our playground represents a torus (borders are connected).
virtual Coord getRandomPosition ()
Random position somewhere in the playground.
bool use2D ()
Returns true if the world is 2-dimensional.
long getUniqueAirFrameId ()
Returns an Id for an AirFrame, at the moment simply an incremented long-value.
Static Public Attributes
static const double speedOfLight = 299792458.0
Speed of light in meters per second.
Protected Member Functions
virtual void initializeIfNecessary ()
Initializes all members accessible by other modules.
Protected Attributes
Coord playgroundSize
Size of the area the nodes are in (in meters).
bool useTorusFlag
Should the playground be treatend as a torus?
bool use2DFlag
Should the world be 2-dimensional?
long airFrameId
Provides a unique number for AirFrames per simulation.
bool isInitialized
Stores if members are already initialized.
Detailed Description
Provides information and utility methods for the whole simulation.
Definition at line 32 of file BaseWorldUtility.h.
Member Function Documentation
const Coord* BaseWorldUtility::getPgs () [inline]
Returns the playgroundSize.
Note: The playground is in the range [0, playground size]. Meaning the upper borders (at pg-size) as well as the lower borders (at 0) are part of the playground.
Definition at line 81 of file BaseWorldUtility.h.
Referenced by BaseMobility::initialize(), BaseConnectionManager::initialize(), PhyLayer::initializeBreakpointPathlossModel(), PhyLayer::initializeSimplePathlossModel(), MoBANLocal::insideWorld(), MoBANCoordinator::isInsideWorld(), and MoBANCoordinator::mainProcess().
{
      initializeIfNecessary();
        return &playgroundSize;
    };
void BaseWorldUtility::initializeIfNecessary () [protected, virtual]
Initializes all members accessible by other modules.
Called once the first time another module accesses a member or during initialize stage 0 at the latest.
Definition at line 52 of file BaseWorldUtility.cc.
References airFrameId, isInitialized, playgroundSize, use2DFlag, and useTorusFlag.
Referenced by getRandomPosition().
{
  if(isInitialized)
    return;
  use2DFlag      = par("use2D");
  playgroundSize = Coord(par("playgroundSizeX").doubleValue(),
                               par("playgroundSizeY").doubleValue(),
                               use2DFlag ? 0. : par("playgroundSizeZ").doubleValue());
  if(playgroundSize.x < 0) {
    opp_error("Playground size in X direction is invalid: "\
          "(%f). Should be greater than or equal to zero.", playgroundSize.x);
  }
  if(playgroundSize.y < 0) {
    opp_error("Playground size in Y direction is invalid: "\
          "(%f). Should be greater than or equal to zero.", playgroundSize.y);
  }
  if(!use2DFlag && playgroundSize.z < 0) {
    opp_error("Playground size in Z direction is invalid: "\
          "(%f). Should be greater than or equal to zero.", playgroundSize.z);
  }
  useTorusFlag = par("useTorus");
  airFrameId = 0;
  isInitialized = true;
}
Member Data Documentation
Coord BaseWorldUtility::playgroundSize [protected]
Size of the area the nodes are in (in meters).
Note: The playground is in the range [0, playground size]. Meaning the upper borders (at pg-size) as well as the lower borders (at 0) are part of the playground.
Definition at line 42 of file BaseWorldUtility.h.
Referenced by getRandomPosition(), and initializeIfNecessary().
const double BaseWorldUtility::speedOfLight = 299792458.0 [static]
Speed of light in meters per second.
meters per second
Definition at line 58 of file BaseWorldUtility.h.
Referenced by ConnectionManager::calcInterfDist(), SimplePathlossModel::calcPathloss(), ChannelAccess::calculatePropagationDelay(), SimplePathlossModel::filterSignal(), SimplePathlossConstMapping::getValue(), and JakesFadingMapping::getValue().
The documentation for this class was generated from the following files:
src/base/modules/BaseWorldUtility.h
src/base/modules/BaseWorldUtility.cc