MiXiM: DummyRoute Class Reference
DummyRoute Class Reference
[netwLayer - network layer modules]
Placeholder module that simply "translates" netwControlInfo to macControlInfo.
#include <DummyRoute.h>
Inherits BaseNetwLayer.
Public Member Functions
virtual void initialize (int)
Initialization of the module and some variables.
virtual void finish ()
Called when the simulation has finished.
Protected Member Functions
virtual void handleUpperMsg (cMessage *msg)
Handle messages from upper layer.
virtual void handleLowerMsg (cMessage *msg)
Handle messages from lower layer.
virtual void handleSelfMsg (cMessage *)
Handle self messages.
virtual void handleLowerControl (cMessage *msg)
Handle control messages from lower layer.
virtual void handleUpperControl (cMessage *msg)
Handle control messages from lower layer.
virtual NetwPkt * encapsMsg (cPacket *appPkt)
Encapsulate higher layer packet into an NetwPkt.
virtual cPacket * decapsMsg (NetwPkt *msg)
Decapsulate a message.
Protected Attributes
bool stats
bool trace
int networkID
Detailed Description
Placeholder module that simply "translates" netwControlInfo to macControlInfo.
Author:
Jerome Rousselot
Definition at line 28 of file DummyRoute.h.
Member Function Documentation
NetwPkt * DummyRoute::encapsMsg (cPacket * appPkt) [protected, virtual]
Encapsulate higher layer packet into an NetwPkt.
Encapsulates the received ApplPkt into a NetwPkt and set all needed header fields.
Reimplemented from BaseNetwLayer.
Definition at line 66 of file DummyRoute.cc.
References BaseNetwLayer::arp, NetwControlInfo::getAddressFromControlInfo(), ArpInterface::getMacAddr(), BaseNetwLayer::headerLength, LAddress::isL3Broadcast(), LAddress::L2BROADCAST, LAddress::L3BROADCAST, BaseNetwLayer::myNetwAddr, and BaseNetwLayer::setDownControlInfo().
Referenced by handleUpperMsg().
{
    LAddress::L2Type macAddr;
    LAddress::L3Type netwAddr;
    debugEV <<"in encaps...\n";
    DummyRoutePkt *pkt = new DummyRoutePkt(appPkt->getName(), appPkt->getKind());
    pkt->setBitLength(headerLength);
    cObject* cInfo = appPkt->removeControlInfo();
    if(cInfo == NULL){
    EV << "warning: Application layer did not specifiy a destination L3 address\n"
     << "\tusing broadcast address instead\n";
    netwAddr = LAddress::L3BROADCAST;
    } else {
    debugEV <<"CInfo removed, netw addr="<< NetwControlInfo::getAddressFromControlInfo( cInfo ) << endl;
    netwAddr = NetwControlInfo::getAddressFromControlInfo( cInfo );
    delete cInfo;
    }
    pkt->setNetworkID(networkID);
    pkt->setSrcAddr(myNetwAddr);
    pkt->setDestAddr(netwAddr);
    debugEV << " netw "<< myNetwAddr << " sending packet" <<endl;
    if(LAddress::isL3Broadcast(netwAddr)) {
        debugEV << "sendDown: nHop=L3BROADCAST -> message has to be broadcasted"
           << " -> set destMac=L2BROADCAST\n";
        macAddr = LAddress::L2BROADCAST;
    }
    else{
        debugEV <<"sendDown: get the MAC address\n";
        macAddr = arp->getMacAddr(netwAddr);
    }
    setDownControlInfo(pkt, macAddr);
    //encapsulate the application packet
    pkt->encapsulate(appPkt);
    debugEV <<" pkt encapsulated\n";
    return pkt;
}
The documentation for this class was generated from the following files:
src/modules/netw/DummyRoute.h
src/modules/netw/DummyRoute.cc