MiXiM: IntensityModel Class Reference
IntensityModel Class Reference
[analogueModels - AnalogueModel implementations]
TODO: Short description for this AnalogueModel.
#include <IntensityModel.h>
Inherits AnalogueModel.
Public Member Functions
void filterSignal (AirFrame *frame, const Coord &sendersPos, const Coord &receiverPos)
Has to be overriden by every implementation.
Detailed Description
TODO: Short description for this AnalogueModel.
Definition at line 36 of file IntensityModel.h.
Member Function Documentation
void IntensityModel::filterSignal (AirFrame * frame, const Coord & sendersPos, const Coord & receiverPos) [inline, virtual]
Has to be overriden by every implementation.
Filters a specified AirFrame's Signal by adding an attenuation over time to the Signal.
Parameters:
frame The incomming frame.
sendersPos The position of the frame sender.
receiverPos The position of frame receiver.
Implements AnalogueModel.
Definition at line 41 of file IntensityModel.h.
References Signal::addAttenuation(), Coord::distance(), Signal::getReceptionStart(), M_PI, and TimeMapping< Interpolator >::setValue().
{
    Signal&              s          = frame->getSignal();
    TimeMapping<Linear>* attMapping = new TimeMapping<Linear> ();
    // Determine distance between sender and receiver
    assert(s.getReceptionStart() == simTime());
    double distance    = sendersPos.distance(receiverPos);
    Argument arg;
    attMapping->setValue(arg, 4*M_PI*pow(distance, 2));
    s.addAttenuation(attMapping);
  }
The documentation for this class was generated from the following file:
src/modules/analogueModel/IntensityModel.h