MiXiM: Coord Class Reference
Coord Class Reference
[utils - utility classes]
Class for storing 3D coordinates.
#include <Coord.h>
Public Member Functions
Coord ()
Default constructor.
Coord (double x, double y, double z=0.0)
Initializes a coordinate.
Coord (const Coord &pos)
Initializes coordinate from other coordinate.
Coord (const Coord *pos)
Initializes coordinate from other coordinate.
std::string info () const
Returns a string with the value of the coordinate.
Coord & operator*= (double f)
Multiplies this coordinate vector by a real number.
Coord & operator/= (double f)
Divides this coordinate vector by a real number.
Coord & operator+= (const Coord &a)
Adds coordinate vector 'a' to this.
Coord & operator= (const Coord &a)
Assigns coordinate vector 'a' to this.
Coord & operator-= (const Coord &a)
Subtracts coordinate vector 'a' from this.
double distance (const Coord &a) const
Returns the distance to Coord 'a'.
double sqrdist (const Coord &a) const
Returns distance^2 to Coord 'a' (omits calling square root).
double sqrTorusDist (const Coord &b, const Coord &size) const
Returns the squared distance on a torus of this to Coord 'b' (omits calling square root).
double squareLength () const
Returns the square of the length of this Coords position vector.
double length () const
Returns the length of this Coords position vector.
bool isInBoundary (const Coord &lowerBound, const Coord &upperBound) const
Checks if this coordinate is inside a specified rectangle.
Coord min (const Coord &a) const
Returns the minimal coordinates.
Coord max (const Coord &a) const
Returns the maximal coordinates.
Public Attributes
x, y and z coordinate of the position.
double x
double y
double z
Static Public Attributes
static const Coord ZERO = Coord(0.0, 0.0, 0.0)
Constant with all values set to 0.
Friends
Coord operator+ (const Coord &a, const Coord &b)
Adds two coordinate vectors.
Coord operator- (const Coord &a, const Coord &b)
Subtracts two coordinate vectors.
Coord operator* (const Coord &a, double f)
Multiplies a coordinate vector by a real number.
Coord operator/ (const Coord &a, double f)
Divides a coordinate vector by a real number.
bool operator== (const Coord &a, const Coord &b)
Tests whether two coordinate vectors are equal.
bool operator!= (const Coord &a, const Coord &b)
Tests whether two coordinate vectors are not equal.
Detailed Description
Class for storing 3D coordinates.
Some comparison and basic arithmetic operators are implemented.
Author:
Christian Frank
Definition at line 37 of file Coord.h.
Member Function Documentation
bool Coord::isInBoundary (const Coord & lowerBound, const Coord & upperBound) const [inline]
Checks if this coordinate is inside a specified rectangle.
Parameters:
lowerBound The lower bound of the rectangle.
upperBound The upper bound of the rectangle.
Definition at line 218 of file Coord.h.
Referenced by PostureTransition::findAreaType(), BaseMobility::initialize(), and MoBANCoordinator::isInsideWorld().
{
        return  lowerBound.x <= x && x <= upperBound.x &&
                lowerBound.y <= y && y <= upperBound.y &&
                lowerBound.z <= z && z <= upperBound.z;
     }
Coord& Coord::operator= (const Coord & a) [inline]
Assigns coordinate vector 'a' to this.
This operator can change the dimension of the coordinate.
Definition at line 138 of file Coord.h.
{
        x = a.x;
        y = a.y;
        z = a.z;
        return *this;
    }
Friends And Related Function Documentation
bool operator!= (const Coord & a, const Coord & b) [friend]
Tests whether two coordinate vectors are not equal.
Negation of the operator==.
Definition at line 171 of file Coord.h.
{
        return !(a==b);
    }
bool operator== (const Coord & a, const Coord & b) [friend]
Tests whether two coordinate vectors are equal.
Because coordinates are of type double, this is done through the FWMath::close function.
Definition at line 161 of file Coord.h.
{
        // FIXME: this implementation is not transitive
        return FWMath::close(a.x, b.x) && FWMath::close(a.y, b.y) && FWMath::close(a.z, b.z);
    }
The documentation for this class was generated from the following files:
src/base/utils/Coord.h
src/base/utils/Coord.cc