MiXiM: ConcatConstMapping< Operator > Class Template Reference
ConcatConstMapping< Operator > Class Template Reference
[mappingDetails - mostly internal mapping classes]
Defines it values by concatenating one or more Mappings to a reference Mapping.
#include <MappingUtils.h>
Inherits ConstMapping.
Public Member Functions
ConcatConstMapping (const ConcatConstMapping &o)
ConcatConstMapping & operator= (const ConcatConstMapping &copy)
ConcatConstMapping assignment operator.
void swap (ConcatConstMapping &s)
Swaps data with another ConcatConstMapping.
template<class Iterator >
ConcatConstMapping (ConstMapping *refMapping, Iterator first, Iterator last, bool continueOutOfRange=true, Argument::mapped_type_cref oorValue=Argument::MappedZero, Operator op=Operator())
Initializes with the passed reference Mapping, the operator and the Mappings defined by the passed iterator.
ConcatConstMapping (ConstMapping *refMapping, ConstMapping *other, bool continueOutOfRange=true, Argument::mapped_type_cref oorValue=Argument::MappedZero, Operator op=Operator())
Initializes with the passed reference Mapping, the operator and another Mapping to concatenate.
void addMapping (ConstMapping *m)
Adds another Mapping to the list of Mappings to concatenate.
virtual Argument::mapped_type getValue (const Argument &pos) const
Returns the value of this Mapping at the position specified by the passed Argument.
Mapping * createConcatenatedMapping () const
Returns the concatenated Mapping.
virtual ConstMappingIterator * createConstIterator () const
Returns a pointer of a new Iterator which is able to iterate over this Mapping.
virtual ConstMappingIterator * createConstIterator (const Argument &pos) const
Returns a pointer of a new Iterator which is able to iterate over the function. The iterator starts at the passed position.
virtual ConstMapping * constClone () const
returns a deep copy of this mapping instance.
ConstMapping * getRefMapping ()
Returns the pointer to the reference mapping.
Protected Types
typedef std::pair< Dimension,
Argument::const_iterator > DimIteratorPair
typedef std::list< ConstMapping * > MappingSet
Protected Attributes
MappingSet mappings
ConstMapping * refMapping
bool continueOutOfRange
Argument::mapped_type oorValue
Operator op
Detailed Description
template<class Operator>
class ConcatConstMapping< Operator >
Defines it values by concatenating one or more Mappings to a reference Mapping.
Author:
Karl Wessel
Definition at line 2071 of file MappingUtils.h.
Member Function Documentation
template<class Operator > virtual ConstMappingIterator* ConcatConstMapping< Operator >::createConstIterator (const Argument & pos) const [inline, virtual]
Returns a pointer of a new Iterator which is able to iterate over the function. The iterator starts at the passed position.
See class ConstIterator for details.
Implements ConstMapping.
Definition at line 2219 of file MappingUtils.h.
References ConcatConstMapping< Operator >::createConcatenatedMapping(), and ConstMapping::createConstIterator().
{
    if(mappings.empty()) {
      return refMapping->createConstIterator(pos);
    }
    return new ConcatConstMappingIterator(createConcatenatedMapping(), pos);
  }
template<class Operator > virtual ConstMappingIterator* ConcatConstMapping< Operator >::createConstIterator () const [inline, virtual]
Returns a pointer of a new Iterator which is able to iterate over this Mapping.
See class ConstIterator for details.
Implements ConstMapping.
Definition at line 2212 of file MappingUtils.h.
References ConcatConstMapping< Operator >::createConcatenatedMapping(), and ConstMapping::createConstIterator().
{
    if(mappings.empty()) {
      return refMapping->createConstIterator();
    }
    return new ConcatConstMappingIterator(createConcatenatedMapping());
  }
template<class Operator > virtual Argument::mapped_type ConcatConstMapping< Operator >::getValue (const Argument & pos) const [inline, virtual]
Returns the value of this Mapping at the position specified by the passed Argument.
The complexity of this method depends on the actual implementation.
Implements ConstMapping.
Definition at line 2179 of file MappingUtils.h.
References ConstMapping::getValue().
{
    const MappingSet::const_iterator itEnd = mappings.end();
    Argument::mapped_type            res   = refMapping->getValue(pos);
    for (MappingSet::const_iterator it = mappings.begin(); it != itEnd; ++it) {
      res = op(res, (*it)->getValue(pos));
    }
    return res;
  }
template<class Operator > ConcatConstMapping& ConcatConstMapping< Operator >::operator= (const ConcatConstMapping< Operator > & copy) [inline]
ConcatConstMapping assignment operator.
Parameters:
copy A ConcatConstMapping of identical element and allocator types.
All the elements of copy are copied.
Reimplemented from ConstMapping.
Definition at line 2099 of file MappingUtils.h.
References ConcatConstMapping< Operator >::swap().
  {
    ConcatConstMapping tmp(copy); // All resource all allocation happens here.
                                    // If this fails the copy will throw an exception
                                    // and 'this' object is unaffected by the exception.
    swap(tmp);
    return *this;
  }
template<class Operator > void ConcatConstMapping< Operator >::swap (ConcatConstMapping< Operator > & s) [inline]
Swaps data with another ConcatConstMapping.
Parameters:
s A ConcatConstMapping of the same element and allocator types.
This exchanges the elements between two ConcatConstMapping's in constant time. Note that the global std::swap() function is specialized such that std::swap(s1,s2) will feed to this function.
Reimplemented from ConstMapping.
Definition at line 2116 of file MappingUtils.h.
Referenced by ConcatConstMapping< Operator >::operator=().
  {
    ConstMapping::swap(s); // swap the base class members
    /* Swap all D members */
    std::swap(mappings,           s.mappings);
    std::swap(refMapping,         s.refMapping);
    std::swap(continueOutOfRange, s.continueOutOfRange);
    std::swap(oorValue,           s.oorValue);
    std::swap(op,                 s.op);
  }
The documentation for this class was generated from the following file:
src/base/phyLayer/MappingUtils.h