MiXiM: LAddress Class Reference
LAddress Class Reference
Layer address handling helper function.
#include <SimpleAddress.h>
Public Types
typedef long L2Type
Type definition for a L2 (MAC) address.
typedef long L3Type
Type definition for a L3 (Network) address.
Static Public Member Functions
static bool isL2Broadcast (const L2Type &pSrcAddr)
Test if a L2 address (pSrcAddr) is a broadcast address.
static bool isL3Broadcast (const L3Type &pSrcAddr)
Test if a L3 address (pSrcAddr) is a broadcast address.
Static Public Attributes
static const L2Type L2BROADCAST
Broadcast address for L2 addresses.
static const L2Type L2NULL
NULL address for L2 addresses.
static const L3Type L3BROADCAST = LAddress::L3Type(-1)
Broadcast address for L3 addresses.
static const L3Type L3NULL = LAddress::L3Type(0)
NULL address for L3 addresses.
Detailed Description
Layer address handling helper function.
This class helps to make the layer addressing more generic. The type definition for L2, and L3 addresses should be used for address definitions to simplify the switching to other types.
Both types (LAddress::L2Type, LAddress::L3Type) will be used as keys in in STL containers.
Definition at line 40 of file SimpleAddress.h.
Member Typedef Documentation
typedef long LAddress::L2Type
Type definition for a L2 (MAC) address.
The type should support initialization with long/string values and casting to long/double. The type should be also support the ==,<, and > operators.
Definition at line 50 of file SimpleAddress.h.
typedef long LAddress::L3Type
Type definition for a L3 (Network) address.
The type should support initialization with long values and casting to long/double. The type should be also support the ==,<, and > operators.
Definition at line 57 of file SimpleAddress.h.
Member Function Documentation
static bool LAddress::isL2Broadcast (const L2Type & pSrcAddr) [inline, static]
Test if a L2 address (pSrcAddr) is a broadcast address.
Parameters:
pSrcAddr The L2 address which should be tested.
Returns:
True if pSrcAddr is a braodcast address.
Definition at line 74 of file SimpleAddress.h.
Referenced by Mac80211::beginNewCycle(), Mac80211::handleLowerMsg(), CSMAMacLayer::handleLowerMsg(), csma::handleLowerMsg(), BaseMacLayer::handleLowerMsg(), LMacLayer::handleSelfMsg(), BMacLayer::handleSelfMsg(), and Mac80211::retrieveBitrate().
{
#ifdef MIXIM_INET
        return pSrcAddr.isBroadcast();
#else
        return pSrcAddr == L2BROADCAST;
#endif
    }
static bool LAddress::isL3Broadcast (const L3Type & pSrcAddr) [inline, static]
Test if a L3 address (pSrcAddr) is a broadcast address.
Parameters:
pSrcAddr The L3 address which should be tested.
Returns:
True if pSrcAddr is a braodcast address.
Definition at line 87 of file SimpleAddress.h.
Referenced by DummyRoute::encapsMsg(), BaseNetwLayer::encapsMsg(), WiseRoute::handleLowerMsg(), Flood::handleLowerMsg(), and WiseRoute::handleUpperMsg().
{
        return pSrcAddr == L3BROADCAST;
    }
Member Data Documentation
const LAddress::L2Type LAddress::L2BROADCAST [static]
Initial value:
    LAddress::L2Type(-1)
Broadcast address for L2 addresses.
Definition at line 60 of file SimpleAddress.h.
Referenced by ProbabilisticBroadcast::encapsMsg(), Flood::encapsMsg(), DummyRoute::encapsMsg(), BaseNetwLayer::encapsMsg(), WiseRoute::handleLowerMsg(), ProbabilisticBroadcast::handleLowerMsg(), Flood::handleLowerMsg(), WiseRoute::handleSelfMsg(), ProbabilisticBroadcast::handleSelfMsg(), BMacLayer::handleSelfMsg(), WiseRoute::handleUpperMsg(), NetworkStackTrafficGen::sendBroadcast(), and BMacLayer::sendPreamble().
const LAddress::L2Type LAddress::L2NULL [static]
Initial value:
    LAddress::L2Type(0)
NULL address for L2 addresses.
Definition at line 62 of file SimpleAddress.h.
Referenced by BaseArp::getMacAddr(), AlohaMacLayer::initialize(), and BaseMacLayer::initialize().
The documentation for this class was generated from the following files:
src/base/utils/SimpleAddress.h
src/base/utils/SimpleAddress.cc