MiXiM: Mapping Class Reference
Mapping Class Reference
[mapping - classes representing mathematical mappings]
Represents a changeable mapping (mathematical function) from at least time to Argument::mapped_type.
#include <MappingBase.h>
Inherits ConstMapping.
Inherited by BaseDelayedMapping< Mapping >, ConstMappingWrapper, LinearIntplMapping, MultiDimMapping< Interpolator >, MultiDimMapping< Linear >, TimeMapping< Interpolator >, and TimeMapping< Linear >.
Public Types
enum InterpolationMethod { STEPS, NEAREST, LINEAR }
Types of interpolation methods for mappings.
Public Member Functions
Mapping & operator= (const Mapping &copy)
Mapping assignment operator.
void swap (Mapping &s)
Swaps data with another Mapping.
Mapping (const DimensionSet &dims)
Initializes the Mapping with the passed DimensionSet as domain.
Mapping ()
Initializes the Mapping with the time dimension as domain.
Mapping (const Mapping &o)
virtual void setValue (const Argument &pos, argument_value_cref_t value)=0
Changes the value of the Mapping at the specified position.
virtual void appendValue (const Argument &pos, argument_value_cref_t value)
Appends the passed value at the passed position to the mapping. This method assumes that the passed position is after the last key entry of the mapping.
virtual MappingIterator * createIterator ()=0
Returns a pointer of a new Iterator which is able to iterate over the Mapping and can change it.
virtual MappingIterator * createIterator (const Argument &pos)=0
Returns a pointer of a new Iterator which is able to iterate over the function and can change it.
virtual ConstMappingIterator * createConstIterator () const
Returns an ConstMappingIterator by use of the respective implementation of the "createIterator()"-method.
virtual ConstMappingIterator * createConstIterator (const Argument &pos) const
Returns an ConstMappingIterator by use of the respective implementation of the "createIterator()"-method.
virtual Mapping * clone () const =0
Returns a deep copy of this Mapping.
virtual ConstMapping * constClone () const
Returns a deep const copy of this mapping by using the according "clone()"-implementation.
Detailed Description
Represents a changeable mapping (mathematical function) from at least time to Argument::mapped_type.
This class extends the ConstMapping interface with write access.
See ConstMapping for details.
Author:
Karl Wessel
Definition at line 1209 of file MappingBase.h.
Member Enumeration Documentation
enum Mapping::InterpolationMethod
Types of interpolation methods for mappings.
Enumerator:
STEPS
interpolates with next lower entry
NEAREST
interpolates with nearest entry
LINEAR
interpolates linear with next lower and next upper entry constant before the first and after the last entry
Definition at line 1212 of file MappingBase.h.
{
    STEPS,
    NEAREST,
    LINEAR
  };
Constructor & Destructor Documentation
Mapping::Mapping (const DimensionSet & dims) [inline]
Initializes the Mapping with the passed DimensionSet as domain.
The passed DimensionSet has to contain the time dimension!
Definition at line 1255 of file MappingBase.h.
                                   :
    ConstMapping(dims) {}
Member Function Documentation
virtual void Mapping::appendValue (const Argument & pos, argument_value_cref_t value) [inline, virtual]
Appends the passed value at the passed position to the mapping. This method assumes that the passed position is after the last key entry of the mapping.
Depending on the implementation of the underlying method this method could be faster or at least as fast as the "setValue()"-method.
Implementations of the Mapping interface can override this method if appending values to the end of the mapping could be implemented faster than the "setValue()" method. Otherwise this method just calls the "setValue()"-method implementation.
Reimplemented in FilledUpMapping.
Definition at line 1290 of file MappingBase.h.
Referenced by LogNormalShadowing::filterSignal().
{
    setValue(pos, value);
  }
virtual ConstMappingIterator* Mapping::createConstIterator (const Argument & pos) const [inline, virtual]
Returns an ConstMappingIterator by use of the respective implementation of the "createIterator()"-method.
Override this method if your ConstIterator differs from the normal iterator.
Implements ConstMapping.
Reimplemented in ConstMappingWrapper.
Definition at line 1324 of file MappingBase.h.
{
    return dynamic_cast<ConstMappingIterator*>( const_cast<Mapping*>(this)->createIterator(pos) );
  }
virtual ConstMappingIterator* Mapping::createConstIterator () const [inline, virtual]
Returns an ConstMappingIterator by use of the respective implementation of the "createIterator()"-method.
Override this method if your ConstIterator differs from the normal iterator.
Implements ConstMapping.
Reimplemented in ConstMappingWrapper.
Definition at line 1314 of file MappingBase.h.
Referenced by SNRThresholdDecider::checkIfAboveThreshold(), and Decider80211::checkIfSignalOk().
{
    return dynamic_cast<ConstMappingIterator*>( const_cast<Mapping*>(this)->createIterator() );
  }
virtual MappingIterator* Mapping::createIterator (const Argument & pos) [pure virtual]
Returns a pointer of a new Iterator which is able to iterate over the function and can change it.
The iterator starts at the passed position.
Implemented in TimeMapping< Interpolator >, LinearIntplMapping, ConstMappingWrapper, MultiDimMapping< Interpolator >, FilledUpMapping, DelayedMapping, TimeMapping< Linear >, and MultiDimMapping< Linear >.
Mapping& Mapping::operator= (const Mapping & copy) [inline]
Mapping assignment operator.
Parameters:
copy A Mapping of identical element and allocator types.
All the elements of copy are copied.
Reimplemented from ConstMapping.
Reimplemented in LinearIntplMapping, ConstMappingWrapper, MultiDimMapping< Interpolator >, and FilledUpMapping.
Definition at line 1229 of file MappingBase.h.
References ConstMapping::operator=().
  {
    ConstMapping::operator=(copy);
    return *this;
  }
virtual void Mapping::setValue (const Argument & pos, argument_value_cref_t value) [pure virtual]
Changes the value of the Mapping at the specified position.
The complexity of this method depends on the implementation.
Implemented in TimeMapping< Interpolator >, LinearIntplMapping, ConstMappingWrapper, MultiDimMapping< Interpolator >, TimeMapping< Linear >, and MultiDimMapping< Linear >.
Referenced by BaseMacLayer::createConstantMapping(), SimpleMacLayer::createMapping(), Mac80211::createSignal(), BaseMacLayer::createSingleFrequencyMapping(), RandomFrequencyOnlyModel::filterSignal(), and RandomFreqTimeModel::filterSignal().
void Mapping::swap (Mapping & s) [inline]
Swaps data with another Mapping.
Parameters:
s A Mapping of the same element and allocator types.
This exchanges the elements between two DimensionSet's in constant time. Note that the global std::swap() function is specialized such that std::swap(s1,s2) will feed to this function.
Reimplemented from ConstMapping.
Reimplemented in LinearIntplMapping.
Definition at line 1242 of file MappingBase.h.
References ConstMapping::swap().
Referenced by LinearIntplMapping::operator=(), and LinearIntplMapping::swap().
  {
    ConstMapping::swap(s); // swap the base class members
    /* Swap all D members */
  }
The documentation for this class was generated from the following file:
src/base/phyLayer/MappingBase.h