MiXiM: RSAMMapping Class Reference
RSAMMapping Class Reference
[phyLayer - physical layer modules]
This class represents the corresponding mapping to a RadioStateAnalogueModel (RSAM).
#include <PhyUtils.h>
Inherits ConstMapping.
Public Member Functions
RSAMMapping (const RSAMMapping &o)
Copy constructor.
RSAMMapping & operator= (const RSAMMapping &copy)
RSAMMapping assignment operator.
void swap (RSAMMapping &s)
Swaps data with another RSAMMapping.
RSAMMapping (const RadioStateAnalogueModel *rsam, simtime_t_cref signalStart, simtime_t_cref signalEnd)
Constructor taking a pointer to the corresponding RSAM.
virtual argument_value_t getValue (const Argument &pos) const
Returns the value of this Function at position specified by the passed Argument. Zero-time-switches are ignored here, i.e. in case of multiple entries at the same time-point, the last one is significant.
virtual ConstMappingIterator * createConstIterator () const
Returns a pointer of a new Iterator which is able to iterate over the function.
virtual ConstMappingIterator * createConstIterator (const Argument &pos) const
Returns a pointer of a new Iterator which is able to iterate over the function. The iterator starts at the passed position.
virtual ConstMapping * constClone () const
returns a deep copy of this mapping instance.
Protected Attributes
const RadioStateAnalogueModel * rsam
Pointer to the RSAM module.
simtime_t signalStart
Start of the signal this mapping defines attenuation for.
simtime_t signalEnd
End of the signal this mapping defines attenuation for.
Detailed Description
This class represents the corresponding mapping to a RadioStateAnalogueModel (RSAM).
Since RSAM is modified dynamically over time, RSAMMapping doesn't store the information itself, but interacts with its RSAM to obtain information about the mapping.
The relation to RSAM is very tight. RSAM creates an appropriate RSAMMapping by passing a self-pointer to the constructor call.
class RSAMMapping is a friend of class RadioStateAnalogueModel
Definition at line 582 of file PhyUtils.h.
Member Function Documentation
RSAMMapping::argument_value_t RSAMMapping::getValue (const Argument & pos) const [virtual]
Returns the value of this Function at position specified by the passed Argument. Zero-time-switches are ignored here, i.e. in case of multiple entries at the same time-point, the last one is significant.
In this case we have a function: simtime_t -> attenuation
Implements ConstMapping.
Definition at line 337 of file PhyUtils.cc.
References Argument::getTime(), RadioStateAnalogueModel::radioStateAttenuation, and rsam.
{
  // extract the time-component from the argument
  simtime_t_cref t = pos.getTime();
  // assert that t is not before the first timepoint in the RSAM
  // and receiving list is not empty
  assert( !(rsam->radioStateAttenuation.empty()) &&
      !(t < rsam->radioStateAttenuation.front().getTime()) );
  /* receiving list contains at least one entry */
  // set an iterator to the first entry with timepoint > t
  std::list<RadioStateAnalogueModel::ListEntry>::const_iterator it;
  it = upper_bound(rsam->radioStateAttenuation.begin(), rsam->radioStateAttenuation.end(), t);
  // REGULAR CASE: it points to an element that has a predecessor
  --it; // go back one entry, this one is significant!
  return it->getValue();
}
RSAMMapping& RSAMMapping::operator= (const RSAMMapping & copy) [inline]
RSAMMapping assignment operator.
Parameters:
copy A RSAMMapping of identical element and allocator types.
All the elements of copy are copied.
Reimplemented from ConstMapping.
Definition at line 610 of file PhyUtils.h.
References ConstMapping::swap().
{
    RSAMMapping tmp(copy);
    swap(tmp);
    return *this;
  }
void RSAMMapping::swap (RSAMMapping & s) [inline]
Swaps data with another RSAMMapping.
Parameters:
s A RSAMMapping of the same element and allocator types.
This exchanges the elements between two RSAMMapping's in constant time. Note that the global std::swap() function is specialized such that std::swap(s1,s2) will feed to this function.
Reimplemented from ConstMapping.
Definition at line 625 of file PhyUtils.h.
References rsam, signalEnd, signalStart, and ConstMapping::swap().
{
    ConstMapping::swap(s);
    std::swap(rsam,        s.rsam);
    std::swap(signalStart, s.signalStart);
    std::swap(signalEnd,   s.signalEnd);
  }
The documentation for this class was generated from the following files:
src/base/phyLayer/PhyUtils.h
src/base/phyLayer/PhyUtils.cc