MiXiM: Signal Class Reference
Signal Class Reference
[phyLayer - physical layer modules]
The signal class stores the physical representation of the signal of an AirFrame.
#include <Signal_.h>
Public Types
typedef ConcatConstMapping
< std::multiplies< double > > MultipliedMapping
Shortcut type for a concatenated Mapping using multiply operator.
typedef std::list< ConstMapping * > ConstMappingList
Shortcut type for a list of ConstMappings.
Public Member Functions
Signal (simtime_t_cref start=-1.0, simtime_t_cref length=-1.0)
Initializes a signal with the specified start and length.
Signal (const Signal &o)
Overwrites the copy constructor to make sure that the mappings are cloned correct.
Signal & operator= (const Signal &o)
Overwrites the copy operator to make sure that the mappings are cloned correct.
void swap (Signal &)
Swaps data with another Signal.
~Signal ()
Delete the functions of this signal.
simtime_t_cref getSendingStart () const
Returns the point in time when the sending of the Signal started at the sender module.
simtime_t getSendingEnd () const
Returns the point in time when the sending of the Signal ended at the sender module.
simtime_t getReceptionStart () const
Returns the point in time when the receiving of the Signal started at the receiver module. Already includes the propagation delay.
simtime_t getReceptionEnd () const
Returns the point in time when the receiving of the Signal ended at the receiver module. Already includes the propagation delay.
simtime_t_cref getDuration () const
Returns the duration of the signal transmission.
simtime_t_cref getPropagationDelay () const
Returns the propagation delay of the signal.
void setPropagationDelay (simtime_t_cref delay)
Sets the propagation delay of the signal.
void setTransmissionPower (ConstMapping *power)
Sets the function representing the transmission power of the signal.
void setBitrate (Mapping *bitrate)
Sets the function representing the bitrate of the signal.
void addAttenuation (ConstMapping *att)
Adds a function representing an attenuation of the signal.
ConstMapping * getTransmissionPower ()
Returns the function representing the transmission power of the signal.
const ConstMapping * getTransmissionPower () const
Returns the function representing the transmission power of the signal.
Mapping * getBitrate () const
Returns the function representing the bitrate of the signal.
const ConstMappingList & getAttenuation () const
Returns a list of functions representing the attenuations of the signal.
MultipliedMapping * getReceivingPower ()
Calculates and returns the receiving power of this Signal. Ownership of the returned mapping belongs to this class.
cModule * getReceptionModule () const
cGate * getReceptionGate () const
cModule * getSendingModule () const
cGate * getSendingGate () const
void setReceptionSenderInfo (const cMessage *const pMsg)
Saves the arrival sender module information form message.
Protected Member Functions
void markRcvPowerOutdated ()
Deletes the rcvPower mapping member because it became out-dated.
Protected Attributes
int senderModuleID
Sender module id, additional definition here because BasePhyLayer will do some selfMessages with AirFrame.
int senderFromGateID
Sender gate id, additional definition here because BasePhyLayer will do some selfMessages with AirFrame.
int receiverModuleID
Receiver module id, additional definition here because BasePhyLayer will do some selfMessages with AirFrame.
int receiverToGateID
Receiver gate id, additional definition here because BasePhyLayer will do some selfMessages with AirFrame.
simtime_t sendingStart
The start of the signal transmission at the sender module.
simtime_t duration
The duration of the signal transmission.
simtime_t propagationDelay
The propagation delay of the transmission.
ConstMapping * power
Stores the function which describes the power of the signal.
Mapping * bitrate
Stores the function which describes the bitrate of the signal.
Mapping * txBitrate
If propagation delay is not zero this stores the undelayed bitrate.
ConstMappingList attenuations
Stores the functions describing the attenuations of the signal.
MultipliedMapping * rcvPower
Stores the mapping defining the receiving power of the signal.
Detailed Description
The signal class stores the physical representation of the signal of an AirFrame.
This includes start, duration and propagation delay of the signal, Mappings which represent the transmission power, bitrate, attenuations caused by effects of the channel on the signal during its transmission and the receiving power.
Note: Although the Signal itself has a signalSendingStart parameter the Mappings it contains should use absolute time positions to store the values at (NOT relative to the start time of the signal).
The Signal is created at the senders MAC layer which has to define the TX-power- and the bitrate Mapping. Sending start time and duration is added at the sender's physical layer. Attenuation Mappings are added to the Signal by the AnalogueModels of the receiver's physical layer. The RX-power Mapping is calculated on demand by multiplying the TX-power Mapping with every attenuation Mapping of the signal.
Definition at line 33 of file Signal_.h.
Member Typedef Documentation
typedef ConcatConstMapping<std::multiplies<double> > Signal::MultipliedMapping
Shortcut type for a concatenated Mapping using multiply operator.
Used to define the receiving power mapping.
Definition at line 40 of file Signal_.h.
Member Function Documentation
void Signal::addAttenuation (ConstMapping * att) [inline]
Adds a function representing an attenuation of the signal.
The ownership of the passed pointer goes to the signal.
Definition at line 187 of file Signal_.h.
Referenced by UWBIRStochasticPathlossModel::filterSignal(), UWBIRIEEE802154APathlossModel::filterSignal(), SimplePathlossModel::filterSignal(), PERModel::filterSignal(), LogNormalShadowing::filterSignal(), JakesFading::filterSignal(), IntensityModel::filterSignal(), BreakpointPathlossModel::filterSignal(), RadioStateAnalogueModel::filterSignal(), RandomFrequencyOnlyModel::filterSignal(), and RandomFreqTimeModel::filterSignal().
{
    //assert the attenuation wasn't already added to the list before
    assert(std::find(attenuations.begin(), attenuations.end(), att) == attenuations.end());
    attenuations.push_back(att);
    if(rcvPower)
      rcvPower->addMapping(att);
  }
MultipliedMapping* Signal::getReceivingPower () [inline]
Calculates and returns the receiving power of this Signal. Ownership of the returned mapping belongs to this class.
The receiving power is calculated by multiplying the transmission power with the attenuation of every receiving phys AnalogueModel.
Definition at line 242 of file Signal_.h.
References Argument::MappedZero.
Referenced by BaseDecider::calculateRSSIMapping(), BaseDecider::calculateSnrMapping(), SNRThresholdDecider::processNewSignal(), Decider80211::processNewSignal(), and BaseDecider::processNewSignal().
{
    if(!rcvPower)
    {
      ConstMapping* tmp = power;
      if(propagationDelay != 0) {
        tmp = new ConstDelayedMapping(power, propagationDelay);
      }
      rcvPower = new MultipliedMapping(tmp,
                        attenuations.begin(),
                        attenuations.end(),
                        false, Argument::MappedZero);
    }
    return rcvPower;
  }
cGate * Signal::getReceptionGate () const
Returns pointers to the gate from which the signal was sent and on which gate it arrived. A NULL pointer is returned for new (unsent) signal.
Definition at line 197 of file Signal.cc.
References getReceptionModule(), and receiverToGateID.
{
    if (receiverToGateID < 0) return NULL;
    cModule *const mod = getReceptionModule();
    return !mod ? NULL : mod->gate(receiverToGateID);
}
cModule* Signal::getReceptionModule () const [inline]
Returns a pointer to the arrival module. It returns NULL if the signal has not been sent/received yet, or if the module was deleted in the meantime.
Definition at line 263 of file Signal_.h.
Referenced by getReceptionGate().
{return receiverModuleID < 0 ? NULL : simulation.getModule(receiverModuleID);}
cGate * Signal::getSendingGate () const
Returns pointers to the gate from which the signal was sent and on which gate it arrived. A NULL pointer is returned for new (unsent) signal.
Definition at line 190 of file Signal.cc.
References getSendingModule(), and senderFromGateID.
{
    if (senderFromGateID < 0) return NULL;
    cModule *const mod = getSendingModule();
    return !mod ? NULL : mod->gate(senderFromGateID);
}
cModule* Signal::getSendingModule () const [inline]
Returns a pointer to the sender module. It returns NULL if the signal has not been sent/received yet, or if the sender module got deleted in the meantime.
Definition at line 277 of file Signal_.h.
Referenced by getSendingGate().
{return senderModuleID < 0 ? NULL : simulation.getModule(senderModuleID);}
const ConstMapping* Signal::getTransmissionPower () const [inline]
Returns the function representing the transmission power of the signal.
Be aware that the transmission power mapping is not yet affected by the propagation delay!
Definition at line 215 of file Signal_.h.
{
    return power;
  }
ConstMapping* Signal::getTransmissionPower () [inline]
Returns the function representing the transmission power of the signal.
Be aware that the transmission power mapping is not yet affected by the propagation delay!
Definition at line 204 of file Signal_.h.
Referenced by UWBIRIEEE802154APathlossModel::filterSignal(), and SimplePathlossModel::filterSignal().
{
    return power;
  }
void Signal::markRcvPowerOutdated () [inline, protected]
Deletes the rcvPower mapping member because it became out-dated.
This happens when transmission power or propagation delay changes.
Definition at line 82 of file Signal_.h.
Referenced by operator=(), setPropagationDelay(), and setTransmissionPower().
{
    if(rcvPower){
      if(propagationDelay != 0) {
        assert(rcvPower->getRefMapping() != power);
        delete rcvPower->getRefMapping();
      }
      delete rcvPower;
      rcvPower = 0;
    }
  }
void Signal::setBitrate (Mapping * bitrate)
Sets the function representing the bitrate of the signal.
The ownership of the passed pointer goes to the signal.
Definition at line 180 of file Signal.cc.
References txBitrate.
Referenced by SimpleMacLayer::createMacPkt(), Mac80211::createSignal(), and BaseMacLayer::createSignal().
{
  assert(!txBitrate);
  if(this->bitrate)
    delete this->bitrate;
  this->bitrate = bitrate;
}
void Signal::setPropagationDelay (simtime_t_cref delay)
Sets the propagation delay of the signal.
This should be only set by the sending physical layer.
Definition at line 156 of file Signal.cc.
References bitrate, markRcvPowerOutdated(), propagationDelay, and txBitrate.
Referenced by BasePhyLayer::handleAirFrameStartReceive().
{
  assert(propagationDelay == 0);
  assert(!txBitrate);
  markRcvPowerOutdated();
  propagationDelay = delay;
  if(bitrate) {
    txBitrate = bitrate;
    bitrate = new DelayedMapping(txBitrate, propagationDelay);
  }
}
void Signal::setTransmissionPower (ConstMapping * power)
Sets the function representing the transmission power of the signal.
The ownership of the passed pointer goes to the signal.
Definition at line 170 of file Signal.cc.
References markRcvPowerOutdated().
Referenced by SimpleMacLayer::createMacPkt(), Mac80211::createSignal(), BaseMacLayer::createSignal(), and UWBIRIEEE802154APathlossModel::filterSignal().
{
  if(this->power){
    markRcvPowerOutdated();
    delete this->power;
  }
  this->power = power;
}
void Signal::swap (Signal & s)
Swaps data with another Signal.
Parameters:
s A Signal of the same element and allocator types.
This exchanges the elements between two Signal's in constant time. Note that the global std::swap() function is specialized such that std::swap(s1,s2) will feed to this function.
Definition at line 90 of file Signal.cc.
References attenuations, bitrate, duration, power, propagationDelay, rcvPower, receiverModuleID, receiverToGateID, senderFromGateID, senderModuleID, sendingStart, and txBitrate.
{
  std::swap(senderModuleID,   s.senderModuleID);
  std::swap(senderFromGateID, s.senderFromGateID);
  std::swap(receiverModuleID, s.receiverModuleID);
  std::swap(receiverToGateID, s.receiverToGateID);
  std::swap(sendingStart,     s.sendingStart);
  std::swap(duration,         s.duration);
  std::swap(propagationDelay, s.propagationDelay);
  std::swap(power,            s.power);
  std::swap(bitrate,          s.bitrate);
  std::swap(txBitrate,        s.txBitrate);
  std::swap(attenuations,     s.attenuations);
  std::swap(rcvPower,         s.rcvPower);
}
The documentation for this class was generated from the following files:
src/base/phyLayer/Signal_.h
src/base/phyLayer/Signal.cc