MiXiM: MacToPhyControlInfo Class Reference
MacToPhyControlInfo Class Reference
[phyLayer - physical layer modules, macLayer - MAC layer modules]
Stores information which is needed by the physical layer when sending a MacPkt.
#include <MacToPhyControlInfo.h>
Inherited by MacToUWBIRPhyControlInfo.
Public Member Functions
MacToPhyControlInfo (Signal *signal=NULL)
Initialize the MacToPhyControlInfo with the passed signal or null if signal is ommited.
virtual ~MacToPhyControlInfo ()
Delete the signal if it is still in our ownership.
void setSignal (Signal *s)
Sets the signal of this MacToPhyControlInfo.
Signal * retrieveSignal ()
Returns a pointer to the Signal of this ControlInfo.
Static Public Member Functions
static cObject * setControlInfo (cMessage *const pMsg, Signal *const pSignal)
Attaches a "control info" structure (object) to the message pMsg.
static Signal * getSignal (cMessage *const pMsg)
extracts the signal from message "control info".
static Signal * getSignalFromControlInfo (cObject *const pCtrlInfo)
extracts the signal from "control info".
Protected Member Functions
MacToPhyControlInfo (const MacToPhyControlInfo &o)
MacToPhyControlInfo & operator= (const MacToPhyControlInfo &o)
Protected Attributes
Signal * signal
A pointer to the signal representing the transmission.
Detailed Description
Stores information which is needed by the physical layer when sending a MacPkt.
Definition at line 14 of file MacToPhyControlInfo.h.
Constructor & Destructor Documentation
MacToPhyControlInfo::MacToPhyControlInfo (Signal * signal = NULL) [inline]
Initialize the MacToPhyControlInfo with the passed signal or null if signal is ommited.
NOTE: Once a signal is passed to the MacToPhyControlInfo, MacToPhyControlInfo takes the ownership of the Signal.
Definition at line 37 of file MacToPhyControlInfo.h.
    : cObject()
    , signal(signal)
  {}
Member Function Documentation
Signal* MacToPhyControlInfo::retrieveSignal () [inline]
Returns a pointer to the Signal of this ControlInfo.
NOTE: The ownership of the Signal is passed together with the Signal itself. This means the caller of this method is responsible for deletion of the Signal. MacToPhyControlInfo also loses its pointer to the Signal when this Method is called so following calls of this method will return null!
Definition at line 73 of file MacToPhyControlInfo.h.
Referenced by MacToUWBIRPhyControlInfo::getSignalFromControlInfo(), and getSignalFromControlInfo().
{
    Signal* tmp = signal;
    signal = NULL;
    return tmp;
  }
static cObject* MacToPhyControlInfo::setControlInfo (cMessage *const pMsg, Signal *const pSignal) [inline, static]
Attaches a "control info" structure (object) to the message pMsg.
This is most useful when passing packets between protocol layers of a protocol stack, the control info will contain the signal.
The "control info" object will be deleted when the message is deleted. Only one "control info" structure can be attached (the second setL3ToL2ControlInfo() call throws an error).
Parameters:
pMsg The message where the "control info" shall be attached.
pSignal The signal which should be send.
Definition at line 92 of file MacToPhyControlInfo.h.
Referenced by SimpleMacLayer::createMacPkt(), and BaseMacLayer::setDownControlInfo().
{
      MacToPhyControlInfo *const cCtrlInfo = new MacToPhyControlInfo(pSignal);
      pMsg->setControlInfo(cCtrlInfo);
      return cCtrlInfo;
    }
void MacToPhyControlInfo::setSignal (Signal * s) [inline]
Sets the signal of this MacToPhyControlInfo.
NOTE: Once a signal is passed to the MacToPhyControlInfo, MacToPhyControlInfo takes the ownership of the Signal.
Definition at line 56 of file MacToPhyControlInfo.h.
{
    if(signal)
      delete signal;
    signal = s;
  }
The documentation for this class was generated from the following file:
src/base/phyLayer/MacToPhyControlInfo.h