MiXiM: TimeMapping< Interpolator > Class Template Reference
TimeMapping< Interpolator > Class Template Reference
[mapping - classes representing mathematical mappings]
Implements the Mapping-interface with an InterpolateableMap from simtime_t to double between which values can be interpolated to represent a Mapping with only time as domain.
#include <MappingUtils.h>
Inherits Mapping.
Public Member Functions
TimeMapping ()
Initializes the Mapping with the passed Interpolation method.
TimeMapping (const TimeMapping< Interpolator > &o)
TimeMapping (mapped_cref_type outOfRangeVal)
Initializes the Mapping with the passed Interpolation method.
virtual Mapping * clone () const
returns a deep copy of this mapping instance.
virtual argument_value_t getValue (const Argument &pos) const
Returns the value of this Function at the position specified by the passed Argument.
virtual void setValue (const Argument &pos, argument_value_cref_t value)
Changes the value of the function at the specified position.
virtual MappingIterator * createIterator ()
Returns a pointer of a new Iterator which is able to iterate over the function and can change the value the iterator points to.
virtual MappingIterator * createIterator (const Argument &pos)
Returns a pointer of a new Iterator which is able to iterate over the function and can change the value the iterator points to.
Protected Types
typedef InterpolateableMap
< Interpolator< std::map
< simtime_t, argument_value_t > > > interpolator_map_type
The templated InterpolateableMap the underlying Mapping uses std::map as storage type.
typedef
interpolator_map_type::interpolator_type interpolator_type
typedef
interpolator_map_type::mapped_type mapped_type
typedef
interpolator_map_type::mapped_cref_type mapped_cref_type
typedef
interpolator_map_type::iterator_intpl iterator
typedef
interpolator_map_type::const_iterator_intpl const_iterator
Protected Attributes
interpolator_map_type entries
Stores the key-entries defining the function.
Detailed Description
template<template< typename > class Interpolator>
class TimeMapping< Interpolator >
Implements the Mapping-interface with an InterpolateableMap from simtime_t to double between which values can be interpolated to represent a Mapping with only time as domain.
Author:
Karl Wessel
Definition at line 316 of file MappingUtils.h.
Member Function Documentation
template<template< typename > class Interpolator> virtual MappingIterator* TimeMapping< Interpolator >::createIterator (const Argument & pos) [inline, virtual]
Returns a pointer of a new Iterator which is able to iterate over the function and can change the value the iterator points to.
Note: The caller of this method has to delete the returned Iterator pointer if it isn't used anymore.
Implements Mapping.
Definition at line 389 of file MappingUtils.h.
{
    return new TimeMappingIterator<Interpolator>(entries.findIntpl(pos.getTime()));
  }
template<template< typename > class Interpolator> virtual MappingIterator* TimeMapping< Interpolator >::createIterator () [inline, virtual]
Returns a pointer of a new Iterator which is able to iterate over the function and can change the value the iterator points to.
Note: The caller of this method has to delete the returned Iterator pointer if it isn't used anymore.
Implements Mapping.
Definition at line 378 of file MappingUtils.h.
Referenced by UWBIRIEEE802154APathlossModel::filterSignal().
{
    return new TimeMappingIterator<Interpolator>(entries.beginIntpl());
  }
template<template< typename > class Interpolator> virtual argument_value_t TimeMapping< Interpolator >::getValue (const Argument & pos) const [inline, virtual]
Returns the value of this Function at the position specified by the passed Argument.
This method has logarithmic complexity.
Implements ConstMapping.
Definition at line 357 of file MappingUtils.h.
{
    return *entries.getIntplValue(pos.getTime());
  }
template<template< typename > class Interpolator> virtual void TimeMapping< Interpolator >::setValue (const Argument & pos, argument_value_cref_t value) [inline, virtual]
Changes the value of the function at the specified position.
This method has logarithmic complexity.
Implements Mapping.
Definition at line 367 of file MappingUtils.h.
Referenced by UWBIRStochasticPathlossModel::filterSignal(), PERModel::filterSignal(), IntensityModel::filterSignal(), and BreakpointPathlossModel::filterSignal().
{
    entries[pos.getTime()] = value;
  }
The documentation for this class was generated from the following file:
src/base/phyLayer/MappingUtils.h