MiXiM: NetwControlInfo Class Reference
NetwControlInfo Class Reference
[utils - utility classes, baseUtils - utilities for base MiXiM, netwLayer - network layer modules, applLayer - application layer modules]
Control info netw messages.
#include <NetwControlInfo.h>
Inherited by ProbBcastNetwControlInfo.
Public Member Functions
NetwControlInfo (const LAddress::L3Type &addr=LAddress::L3NULL)
Default constructor.
virtual ~NetwControlInfo ()
Destructor.
virtual const LAddress::L3Type & getNetwAddr () const
Getter method.
virtual void setNetwAddr (const LAddress::L3Type &addr)
Setter method.
Static Public Member Functions
static cObject * setControlInfo (cMessage *const pMsg, const LAddress::L3Type &pAddr)
Attaches a "control info" structure (object) to the message pMsg.
static const LAddress::L3Type & getAddressFromControlInfo (cObject *const pCtrlInfo)
extracts the address from "control info".
Protected Attributes
LAddress::L3Type netwAddr
netw address of the sending or receiving node
Detailed Description
Control info netw messages.
Control Info to pass interface information from the network to the application layer and vice versa. The application layer passes the destination netw address to the network layer, whereas the network layer uses the control info to pass the source netw address to the application layer
Author:
Daniel Willkomm
Definition at line 45 of file NetwControlInfo.h.
Member Function Documentation
static cObject* NetwControlInfo::setControlInfo (cMessage *const pMsg, const LAddress::L3Type & pAddr) [inline, static]
Attaches a "control info" structure (object) to the message pMsg.
This is most useful when passing packets between protocol layers of a protocol stack, the control info will contain the destination MAC address.
The "control info" object will be deleted when the message is deleted. Only one "control info" structure can be attached (the second setL3ToL2ControlInfo() call throws an error).
Parameters:
pMsg The message where the "control info" shall be attached.
pAddr The network address of to save.
Definition at line 81 of file NetwControlInfo.h.
Referenced by TrafficGen::sendBroadcast(), TestApplLayer::sendBroadcast(), SensorApplLayer::sendData(), and BaseNetwLayer::setUpControlInfo().
{
      NetwControlInfo *const cCtrlInfo = new NetwControlInfo(pAddr);
      pMsg->setControlInfo(cCtrlInfo);
      return cCtrlInfo;
    }
The documentation for this class was generated from the following file:
src/base/utils/NetwControlInfo.h