MiXiM: JakesFading Class Reference
JakesFading Class Reference
[analogueModels - AnalogueModel implementations]
Implements Rayleigh fading after Jakes' model.
#include <JakesFading.h>
Inherits AnalogueModel.
Public Member Functions
JakesFading (int fadingPaths, simtime_t_cref delayRMS, double carrierFrequency, simtime_t_cref interval)
Takes the number of fading paths, the maximum delay on a path, the hosts move, the carrier frequency used and the interval in which to defien attenuation entries in. *.
virtual void filterSignal (AirFrame *, const Coord &, const Coord &)
Has to be overriden by every implementation.
Protected Attributes
int fadingPaths
Number of fading paths used.
double * angleOfArrival
Angle of arrival on a fading path used for Doppler shift calculation.
simtime_t * delay
Delay on a fading path.
double carrierFrequency
Carrier frequency to be used.
Argument interval
The interval to set attenuation entries in.
Private Member Functions
JakesFading (const JakesFading &)
Copy constructor is not allowed.
JakesFading & operator= (const JakesFading &)
Assignment operator is not allowed.
Friends
class JakesFadingMapping
Detailed Description
Implements Rayleigh fading after Jakes' model.
An example config.xml for this AnalogueModel can be the following:
    <AnalogueModel type="JakesFading">
        <!-- Carrier frequency of the signal in Hz
             If ommited the carrier frequency from the
             connection manager is taken if available
             otherwise set to default frequency of 2.412e+9-->
        <parameter name="carrierFrequency" type="double" value="2.412e+9"/>
        <!-- Number of fading paths per host -->
        <parameter name="fadingPaths" type="long" value="3"/>
        <!-- f-selectivity: mean delay spread in seconds -->
        <parameter name="delayRMS" type="double" value="0.0001"/>
        <!-- Interval in which to define attenuation for in seconds -->
        <parameter name="interval" type="double" value="0.001"/>
    </AnalogueModel>
Author:
Hermann S. Lichte, Karl Wessel (port for MiXiM)
Definition at line 109 of file JakesFading.h.
Member Function Documentation
void JakesFading::filterSignal (AirFrame * frame, const Coord & sendersPos, const Coord & receiverPos) [virtual]
Has to be overriden by every implementation.
Filters a specified AirFrame's Signal by adding an attenuation over time to the Signal.
Parameters:
frame The incomming frame.
sendersPos The position of the frame sender.
receiverPos The position of frame receiver.
Implements AnalogueModel.
Definition at line 90 of file JakesFading.cc.
References Signal::addAttenuation(), BaseMobility::getCurrentSpeed(), Signal::getReceptionEnd(), Signal::getReceptionStart(), and interval.
{
  Signal&                signal           = frame->getSignal();
  ChannelMobilityPtrType senderMobility   = dynamic_cast<ChannelAccess *>(frame->getSenderModule())->getMobilityModule();
  ChannelMobilityPtrType receiverMobility = dynamic_cast<ChannelAccess *>(frame->getArrivalModule())->getMobilityModule();
  const double           relSpeed         = (senderMobility->getCurrentSpeed() - receiverMobility->getCurrentSpeed()).length();
  signal.addAttenuation(new JakesFadingMapping(this, relSpeed,
                                               Argument(signal.getReceptionStart()),
                                               interval,
                                               Argument(signal.getReceptionEnd())));
}
The documentation for this class was generated from the following files:
src/modules/analogueModel/JakesFading.h
src/modules/analogueModel/JakesFading.cc