MiXiM: TimeMappingIterator< Interpolator > Class Template Reference
TimeMappingIterator< Interpolator > Class Template Reference
[mapping - classes representing mathematical mappings]
Provides an implementation of the MappingIterator- Interface which is able to iterate over TimeMappings.
#include <MappingUtils.h>
Inherits MappingIterator.
Public Member Functions
TimeMappingIterator (const iterator &it)
Initializes the Iterator to use the passed InterpolateableMapIterator.
TimeMappingIterator (const TimeMappingIterator< Interpolator > &o)
void jumpTo (const Argument &pos)
Lets the iterator point to the passed position.
void iterateTo (const Argument &pos)
Iterates to the specified position. This method should be used if the new position is near the current position.
virtual void next ()
Iterates to the next position of the function.
virtual bool inRange () const
Returns true if the current position of the iterator is in range of the function.
virtual const Argument & getPosition () const
Returns the current position of the iterator.
virtual const Argument & getNextPosition () const
Returns the next position a call to "next()" would jump to.
virtual mapped_type getValue () const
Returns the value of the function at the current position.
virtual void jumpToBegin ()
Lets the iterator point to the begin of the mapping.
virtual bool hasNext () const
Returns true if the iterator has a next value inside its range a call to "next()" can jump to.
virtual void setValue (argument_value_cref_t value)
Changes the value of the function at the current position.
Protected Types
typedef InterpolateableMap
< Interpolator< std::map
< simtime_t, argument_value_t > > > interpolator_map_type
The templated InterpolateableMap the underlying Mapping uses std::map as storage type.
typedef
interpolator_map_type::interpolator_type interpolator_type
typedef
interpolator_map_type::mapped_type mapped_type
typedef
interpolator_map_type::iterator_intpl iterator
typedef
interpolator_map_type::const_iterator_intpl const_iterator
Protected Member Functions
void updateNextPos ()
Protected Attributes
iterator valueIt
Stores the current position iterator inside the Mapping.
Argument position
Stores the current position of the iterator.
Argument nextPosition
Stores the next position a call of "next()" would jump to.
bool isStepMapping
Stores if this mapping represents a step function.
bool atPreStep
Detailed Description
template<template< typename > class Interpolator>
class TimeMappingIterator< Interpolator >
Provides an implementation of the MappingIterator- Interface which is able to iterate over TimeMappings.
Author:
Karl Wessel
Definition at line 112 of file MappingUtils.h.
Member Function Documentation
template<template< typename > class Interpolator> virtual const Argument& TimeMappingIterator< Interpolator >::getNextPosition () const [inline, virtual]
Returns the next position a call to "next()" would jump to.
This method has constant complexity.
Implements ConstMappingIterator.
Definition at line 259 of file MappingUtils.h.
References TimeMappingIterator< Interpolator >::nextPosition.
{
    return nextPosition;
  }
template<template< typename > class Interpolator> virtual const Argument& TimeMappingIterator< Interpolator >::getPosition () const [inline, virtual]
Returns the current position of the iterator.
This method has constant complexity.
Implements ConstMappingIterator.
Definition at line 250 of file MappingUtils.h.
References TimeMappingIterator< Interpolator >::position.
{
    return position;
  }
template<template< typename > class Interpolator> virtual mapped_type TimeMappingIterator< Interpolator >::getValue () const [inline, virtual]
Returns the value of the function at the current position.
This method has constant complexity.
Implements ConstMappingIterator.
Definition at line 269 of file MappingUtils.h.
References TimeMappingIterator< Interpolator >::valueIt.
{
    return *valueIt.getValue();
  }
template<template< typename > class Interpolator> virtual bool TimeMappingIterator< Interpolator >::hasNext () const [inline, virtual]
Returns true if the iterator has a next value inside its range a call to "next()" can jump to.
Constant complexity.
Implements ConstMappingIterator.
Definition at line 292 of file MappingUtils.h.
References TimeMappingIterator< Interpolator >::valueIt.
{
      return valueIt.hasNext();
    }
template<template< typename > class Interpolator> virtual bool TimeMappingIterator< Interpolator >::inRange () const [inline, virtual]
Returns true if the current position of the iterator is in range of the function.
This method should be used as end-condition when iterating over the function with the "next()" method.
THis method has constant complexity.
Implements ConstMappingIterator.
Definition at line 241 of file MappingUtils.h.
References TimeMappingIterator< Interpolator >::valueIt.
{
    return valueIt.inRange();
  }
template<template< typename > class Interpolator> void TimeMappingIterator< Interpolator >::iterateTo (const Argument & pos) [inline, virtual]
Iterates to the specified position. This method should be used if the new position is near the current position.
The passed position should compared bigger than the current position.
This method has linear complexity over the number of key-entries between the current position and the passed position. So if the passed position is near the current position the complexity is nearly constant.
Implements ConstMappingIterator.
Definition at line 205 of file MappingUtils.h.
References Argument::getTime(), TimeMappingIterator< Interpolator >::nextPosition, TimeMappingIterator< Interpolator >::position, Argument::setTime(), and TimeMappingIterator< Interpolator >::valueIt.
{
    atPreStep = false;
    valueIt.iterateTo(pos.getTime());
    position.setTime(pos.getTime());
    nextPosition.setTime(valueIt.getNextPosition());
  }
template<template< typename > class Interpolator> void TimeMappingIterator< Interpolator >::jumpTo (const Argument & pos) [inline, virtual]
Lets the iterator point to the passed position.
The passed new position can be at arbitrary places.
This method has logarithmic complexity.
Implements ConstMappingIterator.
Definition at line 187 of file MappingUtils.h.
References Argument::getTime(), TimeMappingIterator< Interpolator >::nextPosition, TimeMappingIterator< Interpolator >::position, Argument::setTime(), and TimeMappingIterator< Interpolator >::valueIt.
{
    atPreStep = false;
    valueIt.jumpTo(pos.getTime());
    position.setTime(pos.getTime());
    nextPosition.setTime(valueIt.getNextPosition());
  }
template<template< typename > class Interpolator> virtual void TimeMappingIterator< Interpolator >::jumpToBegin () [inline, virtual]
Lets the iterator point to the begin of the mapping.
The beginning of the mapping is the smallest key entry in the InterpolateableMap.
Constant complexity.
Implements ConstMappingIterator.
Definition at line 281 of file MappingUtils.h.
References TimeMappingIterator< Interpolator >::position, Argument::setTime(), and TimeMappingIterator< Interpolator >::valueIt.
{
    valueIt.jumpToBegin();
    position.setTime(valueIt.getPosition());
  }
template<template< typename > class Interpolator> virtual void TimeMappingIterator< Interpolator >::next () [inline, virtual]
Iterates to the next position of the function.
The next position is the next bigger key entry of the InterpoalteableMap.
This method has constant complexity.
Implements ConstMappingIterator.
Definition at line 220 of file MappingUtils.h.
References Argument::getTime(), TimeMappingIterator< Interpolator >::isStepMapping, TimeMappingIterator< Interpolator >::nextPosition, TimeMappingIterator< Interpolator >::position, Argument::setTime(), and TimeMappingIterator< Interpolator >::valueIt.
                      {
    if(isStepMapping && !atPreStep){
      valueIt.iterateTo(nextPosition.getTime());
      atPreStep = true;
    } else {
      valueIt.next();
      atPreStep = false;
    }
    position.setTime(valueIt.getPosition());
    updateNextPos();
  }
template<template< typename > class Interpolator> virtual void TimeMappingIterator< Interpolator >::setValue (argument_value_cref_t value) [inline, virtual]
Changes the value of the function at the current position.
This method has constant complexity.
Implements MappingIterator.
Definition at line 302 of file MappingUtils.h.
References TimeMappingIterator< Interpolator >::valueIt.
{
    valueIt.setValue(value);
  }
Member Data Documentation
template<template< typename > class Interpolator> bool TimeMappingIterator< Interpolator >::isStepMapping [protected]
Stores if this mapping represents a step function.
Assures that the steps are considered when iterating the mapping by adding a second key-entry as short as possible before every key entry set by the user. The additional key-entry defines the value the mapping has just before the key entry the user added.
Definition at line 139 of file MappingUtils.h.
Referenced by TimeMappingIterator< Interpolator >::next(), and TimeMappingIterator< Interpolator >::TimeMappingIterator().
The documentation for this class was generated from the following file:
src/base/phyLayer/MappingUtils.h