MiXiM: MacToNetwControlInfo Class Reference
MacToNetwControlInfo Class Reference
[baseUtils - utilities for base MiXiM, macLayer - MAC layer modules, netwLayer - network layer modules]
Stores control information from mac to upper layer.
#include <MacToNetwControlInfo.h>
Public Member Functions
MacToNetwControlInfo (const LAddress::L2Type &lastHop, double ber=0, double rssi=0)
Initializes with the passed last hop address and bit error rate.
double getBitErrorRate () const
Returns the bit error rate for this packet.
virtual void setBitErrorRate (double ber)
Sets the bit error rate for this control infos packet.
const LAddress::L2Type & getLastHopMac () const
Returns the MAC address of the packets last hop.
virtual void setLastHopMac (const LAddress::L2Type &lastHop)
Sets the MAC address of the packets last hop.
virtual double getRSSI () const
Returns the packets received signal strength.
void setRSSI (double _rssi)
Sets the packets received signal strength.
Static Public Member Functions
static cObject * setControlInfo (cMessage *const pMsg, const LAddress::L2Type &pSrcAddr)
Attaches a "control info" structure (object) to the message pMsg.
static const LAddress::L2Type & getAddress (cMessage *const pMsg)
static const LAddress::L2Type & getAddressFromControlInfo (cObject *const pCtrlInfo)
Protected Attributes
double bitErrorRate
The bit error rate for this packet.
LAddress::L2Type lastHopMac
MAC address of the last hop of this packet.
double rssi
The received signal strength for this packet.
Detailed Description
Stores control information from mac to upper layer.
Holds the bit error rate of the transmission as well as the MAC address of the last hop.
Author:
Karl Wessel
Definition at line 36 of file MacToNetwControlInfo.h.
Member Function Documentation
virtual double MacToNetwControlInfo::getRSSI () const [inline, virtual]
Returns the packets received signal strength.
Returns:
The received signal strength
Definition at line 97 of file MacToNetwControlInfo.h.
{
    return rssi;
  }
virtual void MacToNetwControlInfo::setBitErrorRate (double ber) [inline, virtual]
Sets the bit error rate for this control infos packet.
Parameters:
ber The bit error rate
Definition at line 72 of file MacToNetwControlInfo.h.
Referenced by CSMA802154::decapsMsg().
{
    bitErrorRate = ber;
  }
static cObject* MacToNetwControlInfo::setControlInfo (cMessage *const pMsg, const LAddress::L2Type & pSrcAddr) [inline, static]
Attaches a "control info" structure (object) to the message pMsg.
This is most useful when passing packets between protocol layers of a protocol stack, the control info will contain the source MAC address.
The "control info" object will be deleted when the message is deleted. Only one "control info" structure can be attached (the second setL3ToL2ControlInfo() call throws an error).
Parameters:
pMsg The message where the "control info" shall be attached.
pSrcAddr The MAC address of the message sender.
Definition at line 122 of file MacToNetwControlInfo.h.
Referenced by BaseMacLayer::setUpControlInfo().
{
      MacToNetwControlInfo *const cCtrlInfo = new MacToNetwControlInfo(pSrcAddr);
      pMsg->setControlInfo(cCtrlInfo);
      return cCtrlInfo;
    }
virtual void MacToNetwControlInfo::setLastHopMac (const LAddress::L2Type & lastHop) [inline, virtual]
Sets the MAC address of the packets last hop.
Parameters:
lastHop The last hops MAC address
Definition at line 88 of file MacToNetwControlInfo.h.
{
    lastHopMac = lastHop;
  }
void MacToNetwControlInfo::setRSSI (double _rssi) [inline]
Sets the packets received signal strength.
Parameters:
_rssi The received signal strength
Definition at line 105 of file MacToNetwControlInfo.h.
Referenced by CSMA802154::decapsMsg().
{
    rssi = _rssi;
  }
The documentation for this class was generated from the following file:
src/base/utils/MacToNetwControlInfo.h